const items = {
  trainingSword: { name: "Übungsschwert", slot: "weapon", quality: "common", damage: 4, defense: 0, critChance: 0.01 },
  wornBuckler: { name: "Abgenutzter Buckler", slot: "offhand", quality: "common", damage: 0, defense: 2 },
  paddedVest: { name: "Gepolsterte Weste", slot: "chest", quality: "common", damage: 0, defense: 3 },
  patchedTrousers: { name: "Geflickte Hose", slot: "pants", quality: "common", damage: 0, defense: 2 },
  travelBoots: { name: "Reisestiefel", slot: "boots", quality: "common", damage: 0, defense: 1 },
  twineNecklace: { name: "Kordelhalskette", slot: "necklace", quality: "common", damage: 1, defense: 0, critDamage: 0.04 },
  copperRing: { name: "Kupferring", slot: "ring", quality: "common", damage: 2, defense: 0, critChance: 0.01 },
  wolfRing: { name: "Ring des Rudels", slot: "ring", quality: "rare", damage: 3, defense: 0, critChance: 0.03, set: "wolf", effect: "eliteHunter" },
  rustBlade: { name: "Rostklinge", slot: "weapon", quality: "rare", damage: 8, defense: 0, critChance: 0.03, set: "iron", effect: "bleedEdge" },
  tollKnife: { name: "Zollmesser", slot: "weapon", quality: "rare", damage: 10, defense: 0, critChance: 0.04, critDamage: 0.08, set: "iron", effect: "bleedEdge" },
  houndGreaves: { name: "Eisenhund-Stiefel", slot: "boots", quality: "rare", damage: 0, defense: 10, set: "iron", effect: "steadyStep" },
  hideArmor: { name: "Dornenleder", slot: "chest", quality: "rare", damage: 0, defense: 9, set: "wolf", effect: "thornGuard" },
  oathRing: { name: "Eidring", slot: "ring", quality: "epic", damage: 4, defense: 4, critChance: 0.04, set: "iron", effect: "eliteHunter" },
  knightPlate: { name: "Grenzritterplatte", slot: "chest", quality: "epic", damage: 0, defense: 16, set: "iron", effect: "steadfastWard" },
  crowTalisman: { name: "Seuchentalisman", slot: "necklace", quality: "epic", damage: 8, defense: 0, critDamage: 0.16, set: "crypt", effect: "graveCurse" },
  wraithLantern: { name: "Schemenlaterne", slot: "offhand", quality: "epic", damage: 5, defense: 14, set: "crypt", effect: "graveCurse" },
  ashHook: { name: "Aschenhaken", slot: "weapon", quality: "epic", damage: 18, defense: 0, critChance: 0.05, critDamage: 0.12, set: "ashen", effect: "crownBurn" },
  emberClaw: { name: "Glutklaue", slot: "weapon", quality: "legendary", damage: 26, defense: 0, critChance: 0.08, critDamage: 0.22, set: "ashen", effect: "crownBurn" },
  sentinelVisor: { name: "Kronenvisier", slot: "chest", quality: "legendary", damage: 0, defense: 46, set: "ashen", effect: "steadfastWard" },
  guardAxe: { name: "Gardistenaxt", slot: "weapon", quality: "rare", damage: 12, defense: 0, set: "iron", effect: "bleedEdge" },
  cellkeeperBulwark: { name: "Bollwerk des Zellhüters", slot: "offhand", quality: "epic", damage: 3, defense: 17, set: "iron", effect: "cellLock" },
  graveRing: { name: "Grablichtring", slot: "ring", quality: "epic", damage: 8, defense: 0, critChance: 0.04, critDamage: 0.08, set: "crypt", effect: "graveCurse" },
  boneChalice: { name: "Kelch der stillen Knochen", slot: "necklace", quality: "epic", damage: 7, defense: 0, critDamage: 0.14, set: "crypt", effect: "boneLeech" },
  bruteMail: { name: "Schlägerkettenhemd", slot: "chest", quality: "epic", damage: 0, defense: 22, set: "crypt", effect: "bruteThorns" },
  cryptCrusher: { name: "Gruftspalter", slot: "weapon", quality: "epic", damage: 23, defense: 0, critChance: 0.04, critDamage: 0.14, set: "crypt", effect: "breakerMark" },
  wardenChain: { name: "Kette des Aufsehers", slot: "offhand", quality: "epic", damage: 4, defense: 18, set: "iron", effect: "guardBlock" },
  wardenShackle: { name: "Aufseherfessel", slot: "ring", quality: "epic", damage: 7, defense: 0, critChance: 0.03, set: "iron", effect: "chainSnare" },
  forgeHammer: { name: "Hammer des Eidschmieds", slot: "weapon", quality: "legendary", damage: 30, defense: 0, critDamage: 0.34, set: "iron", effect: "oathBreaker" },
  oathMantle: { name: "Eidmantel", slot: "chest", quality: "epic", damage: 0, defense: 30, set: "iron", effect: "steadfastWard" },
  dukeSignet: { name: "Siegel des Herzogs", slot: "ring", quality: "legendary", damage: 15, defense: 0, critChance: 0.06, critDamage: 0.12, set: "iron", effect: "eliteHunter" },
  ironCrownplate: { name: "Eisenkronenplatte", slot: "chest", quality: "legendary", damage: 0, defense: 52, set: "iron", effect: "steadfastWard" },
  emberRosary: { name: "Glutrosenkranz", slot: "necklace", quality: "legendary", damage: 18, defense: 0, critDamage: 0.28, set: "ashen", effect: "echoHeal" },
  emberCenser: { name: "Rauchfass der Glutmesse", slot: "offhand", quality: "legendary", damage: 7, defense: 32, set: "ashen", effect: "emberWard" },
  crownFang: { name: "Kronenfang", slot: "weapon", quality: "legendary", damage: 34, defense: 0, critChance: 0.07, critDamage: 0.24, set: "ashen", effect: "lifeSiphon" },
  royalSpurs: { name: "Königssporn", slot: "boots", quality: "legendary", damage: 0, defense: 28, set: "ashen", effect: "royalPace" },
  ashenGreatsword: { name: "Aschgraues Großschwert", slot: "weapon", quality: "legendary", damage: 28, defense: 0, critChance: 0.04, critDamage: 0.32, set: "ashen", effect: "crownBurn" },
  crownShard: { name: "Splitter der Krone", slot: "ring", quality: "legendary", damage: 14, defense: 0, critChance: 0.05, critDamage: 0.18, set: "ashen", effect: "duelistMark" },
};

const itemEffectCatalog = {
  bleedEdge: {
    name: "Blutkante",
    text: "Treffer haben 8% Chance auf Blutung für 2 Runden.",
    slots: ["weapon"],
    bleedChance: 0.08,
  },
  venomEdge: {
    name: "Giftkante",
    text: "Treffer haben 10% Chance auf Gift für 3 Runden.",
    slots: ["weapon"],
    poisonChance: 0.1,
  },
  guardBlock: {
    name: "Wachblock",
    text: "Der erste Gegentreffer im Kampf wird um 15% reduziert.",
    slots: ["offhand", "chest"],
    firstHitReduction: 0.15,
  },
  cellLock: {
    name: "Zellenschloss",
    text: "Der erste Gegentreffer wird um 12% reduziert und der Konter geschwächt.",
    slots: ["offhand"],
    firstHitReduction: 0.12,
    firstHitWeaken: 0.9,
  },
  thornGuard: {
    name: "Dornenwache",
    text: "Gegentreffer werfen 8% Schaden auf den Gegner zurück.",
    slots: ["offhand", "chest", "pants"],
    thornsRatio: 0.08,
  },
  bruteThorns: {
    name: "Gruftdornen",
    text: "Gegentreffer werfen 10% Schaden auf den Gegner zurück.",
    slots: ["chest", "pants"],
    thornsRatio: 0.1,
  },
  steadfastWard: {
    name: "Standfeste Rune",
    text: "Gegnerische Crit-Chance -3%.",
    slots: ["offhand", "chest", "pants"],
    enemyCritReduction: 0.03,
  },
  steadyStep: {
    name: "Zäher Schritt",
    text: "Haltbarkeitsverlust nach Kämpfen -10%.",
    slots: ["pants", "boots"],
    durabilityReduction: 0.1,
  },
  luckyPouch: {
    name: "Glückstasche",
    text: "Nach Siegen +8% Gold.",
    slots: ["boots", "ring", "necklace"],
    goldBonus: 0.08,
  },
  royalPace: {
    name: "Königsschritt",
    text: "Haltbarkeitsverlust -10% und nach Siegen +8% Gold.",
    slots: ["boots"],
    durabilityReduction: 0.1,
    goldBonus: 0.08,
  },
  eliteHunter: {
    name: "Elitenjäger",
    text: "+6% Crit-Chance gegen Elite-Gegner und Bosse.",
    slots: ["ring", "necklace"],
    eliteCritChance: 0.06,
  },
  duelistMark: {
    name: "Duellzeichen",
    text: "+10% Schaden gegen Elite-Gegner und Bosse.",
    slots: ["weapon", "ring", "necklace"],
    eliteDamageBonus: 0.1,
  },
  breakerMark: {
    name: "Brecherzeichen",
    text: "+8% Schaden und 12% Rüstungsbruch gegen Elite-Gegner und Bosse.",
    slots: ["weapon"],
    eliteDamageBonus: 0.08,
    eliteArmorIgnore: 0.12,
  },
  echoHeal: {
    name: "Nachhall",
    text: "Nach einem Sieg heilt 4% Leben.",
    slots: ["ring", "necklace"],
    postCombatHeal: 0.04,
  },
  boneLeech: {
    name: "Knochenzehrung",
    text: "Kritische Treffer heilen 2% Leben. Nach einem Sieg heilt 3% Leben.",
    slots: ["ring", "necklace"],
    critHealRatio: 0.02,
    postCombatHeal: 0.03,
  },
  lifeSiphon: {
    name: "Lebenssog",
    text: "Kritische Treffer heilen 3% Leben.",
    slots: ["weapon", "ring", "necklace"],
    critHealRatio: 0.03,
  },
  emberWard: {
    name: "Glutweihe",
    text: "Der erste Gegentreffer wird um 12% reduziert. Nach einem Sieg heilt 3% Leben.",
    slots: ["offhand", "necklace"],
    firstHitReduction: 0.12,
    postCombatHeal: 0.03,
  },
  crownBurn: {
    name: "Kronenbrand",
    text: "Kritische Treffer verursachen Brennen für 2 Runden.",
    slots: ["weapon", "ring", "necklace"],
    critBurn: true,
  },
  oathBreaker: {
    name: "Eidbrecher",
    text: "Treffer gegen Elite-Gegner und Bosse ignorieren 18% Rüstung.",
    slots: ["weapon", "offhand"],
    eliteArmorIgnore: 0.18,
  },
  graveCurse: {
    name: "Grabfluch",
    text: "Der erste Treffer schwächt den nächsten Gegenschlag.",
    slots: ["offhand", "ring", "necklace"],
    firstHitWeaken: 0.88,
  },
  chainSnare: {
    name: "Kettenfang",
    text: "Der erste Treffer schwächt den nächsten Gegenschlag stark.",
    slots: ["ring", "offhand"],
    firstHitWeaken: 0.82,
  },
};

const enchantmentCatalog = {
  keenEdge: {
    name: "Scharfe Rune",
    category: "offense",
    rarity: "common",
    group: "critChance",
    slots: ["weapon", "ring", "necklace"],
    stats: { critChance: 0.02 },
    text: "+2% Crit-Chance",
  },
  emberStrike: {
    name: "Glutfunke",
    category: "offense",
    rarity: "common",
    group: "damage",
    slots: ["weapon", "offhand", "ring", "necklace"],
    stats: { damage: 2 },
    text: "+2 Angriff",
  },
  cruelMark: {
    name: "Grausames Zeichen",
    category: "offense",
    rarity: "rare",
    group: "critDamage",
    slots: ["weapon", "ring", "necklace"],
    stats: { critDamage: 0.08 },
    text: "+8% Crit-Schaden",
  },
  bossOath: {
    name: "Boss-Schwur",
    category: "offense",
    rarity: "rare",
    group: "bossDamage",
    slots: ["weapon", "offhand", "ring", "necklace"],
    stats: { bossDamage: 0.06 },
    text: "+6% Schaden gegen Elite und Bosse",
  },
  runicGuard: {
    name: "Wachrune",
    category: "defense",
    rarity: "common",
    group: "defense",
    slots: ["offhand", "chest", "pants", "boots"],
    stats: { defense: 3 },
    text: "+3 Verteidigung",
  },
  lifeThread: {
    name: "Lebensfaden",
    category: "defense",
    rarity: "common",
    group: "maxHp",
    slots: ["chest", "pants", "boots", "necklace", "ring"],
    stats: { maxHp: 14 },
    text: "+14 Leben",
  },
  ironSkin: {
    name: "Eisenhaut",
    category: "defense",
    rarity: "rare",
    group: "damageReduction",
    slots: ["offhand", "chest", "pants"],
    stats: { damageReduction: 0.04 },
    text: "-4% erlittener Schaden",
  },
  wardSpark: {
    name: "Schutzfunke",
    category: "defense",
    rarity: "rare",
    group: "lowHpShield",
    slots: ["chest", "offhand", "necklace"],
    stats: { lowHpShield: 0.08 },
    text: "Unter 35% Leben zählt dein Leben im Risiko höher",
  },
  coinWhisper: {
    name: "Münzflüstern",
    category: "utility",
    rarity: "common",
    group: "goldBonus",
    slots: ["boots", "necklace", "ring"],
    stats: { goldBonus: 0.08 },
    text: "+8% Gold aus Kämpfen",
  },
  scholarDust: {
    name: "Gelehrtenstaub",
    category: "utility",
    rarity: "common",
    group: "xpBonus",
    slots: ["necklace", "ring", "boots"],
    stats: { xpBonus: 0.06 },
    text: "+6% XP aus Kämpfen",
  },
  scavengerRune: {
    name: "Sucherrune",
    category: "utility",
    rarity: "rare",
    group: "lootBonus",
    slots: ["boots", "necklace", "ring"],
    stats: { lootBonus: 0.05 },
    text: "+5% Chance auf bessere Beute",
  },
  menderMark: {
    name: "Pflegezeichen",
    category: "utility",
    rarity: "rare",
    group: "durabilityReduction",
    slots: ["weapon", "offhand", "chest", "pants", "boots"],
    stats: { durabilityReduction: 0.08 },
    text: "-8% Haltbarkeitsverlust",
  },
  warSigil: {
    name: "Kriegssiegel",
    category: "offense",
    rarity: "epic",
    group: "damage",
    slots: ["weapon", "ring", "necklace"],
    stats: { damage: 5, critChance: 0.02 },
    text: "+5 Angriff und +2% Crit-Chance",
  },
  bastionGlyph: {
    name: "Bastionsglyphe",
    category: "defense",
    rarity: "epic",
    group: "damageReduction",
    slots: ["offhand", "chest", "pants"],
    stats: { defense: 5, damageReduction: 0.05 },
    text: "+5 Verteidigung und -5% erlittener Schaden",
  },
  luckyStar: {
    name: "Glücksstern",
    category: "utility",
    rarity: "epic",
    group: "lootBonus",
    slots: ["necklace", "ring"],
    stats: { lootBonus: 0.09, goldBonus: 0.08 },
    text: "+9% bessere Beute und +8% Gold",
  },
  voidEdge: {
    name: "Leerenkante",
    category: "offense",
    rarity: "arcane",
    group: "arcaneDamage",
    slots: ["weapon", "ring", "necklace"],
    stats: { damage: 10, critChance: 0.04, defense: -3 },
    text: "+10 Angriff, +4% Crit-Chance, aber -3 Verteidigung",
  },
  starBulwark: {
    name: "Sternenbann",
    category: "defense",
    rarity: "arcane",
    group: "arcaneShield",
    slots: ["offhand", "chest", "pants"],
    stats: { maxHp: 80, damageReduction: 0.07, critDamage: -0.08 },
    text: "+80 Leben und -7% erlittener Schaden, aber -8% Crit-Schaden",
  },
  fateThread: {
    name: "Schicksalsfaden",
    category: "utility",
    rarity: "arcane",
    group: "arcaneFortune",
    slots: ["boots", "necklace", "ring"],
    stats: { lootBonus: 0.12, xpBonus: 0.12, goldBonus: 0.12, maxHp: -25 },
    text: "+12% Beute, XP und Gold, aber -25 Leben",
  },
};

const enchantmentCategoryLabel = {
  offense: "Offensiv",
  defense: "Defensiv",
  utility: "Utility",
};

const enchantmentRarityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  arcane: "Arkan",
};

const qualityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  legendary: "Legendär",
};

const slotLabel = {
  weapon: "Waffe",
  offhand: "2. Hand",
  chest: "Brustpanzer",
  pants: "Hose",
  boots: "Stiefel",
  necklace: "Halskette",
  ring: "Ring",
};

const equipmentSlots = ["weapon", "offhand", "chest", "pants", "boots", "necklace", "ring"];
const lootSlots = [...equipmentSlots];

const qualityPower = {
  common: 1,
  rare: 1.28,
  epic: 1.62,
  legendary: 2.05,
};

const lootNames = {
  weapon: {
    common: ["Kerbenschwert", "Feldbeil", "Wachklinge"],
    rare: ["Runenklinge", "Blutrost-Axt", "Silberfalchion"],
    epic: ["Eidbrecher", "Sternstahlklinge", "Gruftspalter"],
    legendary: ["Königsschneide", "Aschenurteil", "Drachenzahn"],
  },
  offhand: {
    common: ["Holzschild", "Parierdolch", "Rostbuckler"],
    rare: ["Wolfsbuckler", "Gardistenschild", "Hakenklinge"],
    epic: ["Eidwall", "Runenfokus", "Gruftlaterne"],
    legendary: ["Sonnenschild", "Aschenfokus", "Splitterparade"],
  },
  chest: {
    common: ["Lederwams", "Kettenfetzen", "Reiserüstung"],
    rare: ["Wolfsleder", "Schildplattenrock", "Schuppenpanzer"],
    epic: ["Eidhüterplatte", "Nachtkettenhemd", "Runenharnisch"],
    legendary: ["Krone der Bastion", "Aschenpanzer", "Sonnenharnisch"],
  },
  pants: {
    common: ["Leinenhose", "Wanderbeinlinge", "Kettenhose"],
    rare: ["Wolfsbeinlinge", "Schmiedeplatten", "Räuberhose"],
    epic: ["Eidbeinplatten", "Grabstahl-Beinlinge", "Runenbeinpanzer"],
    legendary: ["Aschenbeinplatten", "Königsgamaschen", "Sonnenbeinschutz"],
  },
  boots: {
    common: ["Lederstiefel", "Marschschuhe", "Eisenkappen"],
    rare: ["Fährtenstiefel", "Wachstiefel", "Dornenläufer"],
    epic: ["Eidtreter", "Gruftschritte", "Runensohlen"],
    legendary: ["Aschenläufer", "Sonnenstiefel", "Kronenschritte"],
  },
  necklace: {
    common: ["Holzamulett", "Kordelkette", "Kupfertalisman"],
    rare: ["Wolfszahnkette", "Rostmedaillon", "Wachhalsreif"],
    epic: ["Eidamulett", "Grablichtkette", "Runenhalsreif"],
    legendary: ["Aschenmedaillon", "Sonnenanhänger", "Kronentalisman"],
  },
  ring: {
    common: ["Zinnring", "Feldreif", "Schlichter Talisman"],
    rare: ["Blutsteinring", "Wolfszeichen", "Wachtersiegel"],
    epic: ["Grablichtreif", "Eidsiegel", "Sternsplitterring"],
    legendary: ["Splitterkrone", "Ring des alten Feuers", "Königszeichen"],
  },
};

const setBonuses = {
  wolf: {
    name: "Rudeljäger",
    bonuses: {
      2: { damage: 3, defense: 1, text: "+3 Schaden, +1 Verteidigung" },
      4: { damage: 5, defense: 4, text: "+5 Schaden, +4 Verteidigung" },
      6: { damage: 11, defense: 7, maxHp: 18, text: "+11 Schaden, +7 Verteidigung, +18 Leben" },
    },
  },
  iron: {
    name: "Grenzwacht",
    bonuses: {
      2: { defense: 5, text: "+5 Verteidigung" },
      4: { damage: 3, defense: 10, text: "+3 Schaden, +10 Verteidigung" },
      6: { damage: 7, defense: 20, maxHp: 26, text: "+7 Schaden, +20 Verteidigung, +26 Leben" },
    },
  },
  crypt: {
    name: "Gruftbund",
    bonuses: {
      2: { damage: 4, maxHp: 12, text: "+4 Schaden, +12 Leben" },
      4: { damage: 7, defense: 6, maxHp: 22, text: "+7 Schaden, +6 Verteidigung, +22 Leben" },
      6: { damage: 13, defense: 11, maxHp: 48, text: "+13 Schaden, +11 Verteidigung, +48 Leben" },
    },
  },
  ashen: {
    name: "Aschenkrone",
    bonuses: {
      2: { damage: 8, defense: 5, text: "+8 Schaden, +5 Verteidigung" },
      4: { damage: 14, defense: 11, maxHp: 32, text: "+14 Schaden, +11 Verteidigung, +32 Leben" },
      6: { damage: 28, defense: 19, maxHp: 64, text: "+28 Schaden, +19 Verteidigung, +64 Leben" },
    },
  },
};
