const saveKey = "fantasy-grind-save-v1";
const saveBackupKey = `${saveKey}-backup`;
const savePreviousKey = `${saveKey}-previous`;
const saveExportVersion = 1;

const xpForLevel = (level) => Math.floor(115 * Math.pow(level, 1.78) + level * 48);

const classCatalog = {
  warrior: {
    name: "Krieger",
    description: "Standhaft, direkt und stark mit Waffen.",
    abilities: ["heavyStrike", "shieldWall", "battleRush"],
  },
};

const buildCatalog = {
  tank: {
    name: "Tank",
    description: "Mehr Leben und Verteidigung. Schildwall ist stärker.",
    damageMultiplier: 0.92,
    defenseMultiplier: 1.18,
    maxHpMultiplier: 1.16,
  },
  damage: {
    name: "Schaden",
    description: "Mehr Schaden, aber etwas weniger Leben.",
    damageMultiplier: 1.16,
    defenseMultiplier: 0.94,
    maxHpMultiplier: 0.94,
  },
  bruiser: {
    name: "Bruiser",
    description: "Ausgewogen. Kampfrausch heilt stärker.",
    damageMultiplier: 1.06,
    defenseMultiplier: 1.06,
    maxHpMultiplier: 1.04,
  },
};

const abilityCatalog = {
  heavyStrike: {
    name: "Schwerer Hieb",
    text: "Jede 3. Runde ein stärkerer Angriff.",
  },
  shieldWall: {
    name: "Schildwall",
    text: "Jede 4. Runde wird der Gegentreffer reduziert.",
  },
  battleRush: {
    name: "Kampfrausch",
    text: "Einmal pro Kampf Heilung, wenn das Leben niedrig ist.",
  },
};

const zones = {
  meadow: {
    name: "Grauwacht-Wald",
    type: "zone",
    range: "Level 1-6",
    unlock: { level: 1, renown: 0 },
    enemies: ["wolf", "bandit", "boar"],
  },
  road: {
    name: "Räuberstraße",
    type: "zone",
    range: "Level 5-11",
    unlock: { level: 5, renown: 0 },
    enemies: ["roadThief", "ironHound", "oldKnight"],
  },
  fields: {
    name: "Verfluchte Felder",
    type: "zone",
    range: "Level 10-16",
    unlock: { level: 9, renown: 8 },
    enemies: ["plagueCrow", "fieldWraith", "oldKnight"],
  },
  ashgrounds: {
    name: "Aschengrund",
    type: "zone",
    range: "Level 15-20",
    unlock: { level: 14, renown: 20 },
    enemies: ["ashMarauder", "emberStalker", "crownSentinel"],
  },
  crypt: {
    name: "Krypta der Grauwacht",
    type: "dungeon",
    range: "Level 9-15",
    unlock: { level: 8, renown: 6 },
    enemies: ["ratguard", "boneAcolyte", "cryptBrute"],
  },
  ironhold: {
    name: "Eisenbruch-Festung",
    type: "dungeon",
    range: "Level 13-18",
    unlock: { level: 12, renown: 14 },
    enemies: ["chainWarden", "oathForger", "ironDuke"],
  },
  ashcathedral: {
    name: "Aschenkathedrale",
    type: "dungeon",
    range: "Level 18-20",
    unlock: { level: 17, renown: 30 },
    enemies: ["emberPriest", "crownBeast", "hollowChampion"],
  },
};

const enemies = {
  wolf: {
    name: "Waldwolf",
    sprite: "enemy-wolf",
    level: 1,
    hp: 44,
    damage: [7, 12],
    defense: 2,
    xp: 16,
    gold: [2, 4],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["common", "rare"] },
    drops: [{ id: "wolfRing", chance: 0.024 }],
    tags: { wolf: 1 },
  },
  bandit: {
    name: "Wegräuber",
    sprite: "enemy-bandit",
    level: 3,
    hp: 72,
    damage: [12, 19],
    defense: 5,
    xp: 30,
    gold: [4, 9],
    generatedLoot: { slots: ["weapon", "offhand", "necklace"], qualities: ["common", "rare"] },
    drops: [{ id: "rustBlade", chance: 0.038 }],
    tags: { bandit: 1, rust: 0.32 },
  },
  roadThief: {
    name: "Straßenräuber",
    sprite: "enemy-bandit",
    level: 5,
    hp: 108,
    damage: [18, 28],
    defense: 8,
    xp: 52,
    gold: [8, 15],
    generatedLoot: { slots: ["weapon", "offhand", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "tollKnife", chance: 0.034 }],
    tags: { bandit: 1, rust: 0.45 },
  },
  ironHound: {
    name: "Eisenhund",
    sprite: "enemy-wolf",
    level: 8,
    hp: 168,
    damage: [27, 39],
    defense: 13,
    xp: 86,
    gold: [10, 19],
    generatedLoot: { slots: ["chest", "boots", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "houndGreaves", chance: 0.026 }],
    tags: { beast: 1, rust: 0.25 },
  },
  boar: {
    name: "Dornenkeiler",
    sprite: "enemy-boar",
    level: 6,
    hp: 122,
    damage: [20, 31],
    defense: 8,
    xp: 62,
    gold: [7, 13],
    generatedLoot: { slots: ["chest", "pants", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "hideArmor", chance: 0.032 }],
    tags: { beast: 1 },
  },
  oldKnight: {
    name: "Alter Grenzritter",
    sprite: "enemy-knight",
    level: 10,
    hp: 210,
    damage: [34, 50],
    defense: 17,
    xp: 120,
    gold: [14, 25],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "oathRing", chance: 0.018 }, { id: "knightPlate", chance: 0.012 }],
    elite: true,
    tags: { elite: 1 },
  },
  plagueCrow: {
    name: "Seuchenkrähe",
    sprite: "enemy-acolyte",
    level: 10,
    hp: 205,
    damage: [35, 52],
    defense: 15,
    xp: 128,
    gold: [15, 27],
    generatedLoot: { slots: ["necklace", "ring", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "crowTalisman", chance: 0.024 }],
    tags: { beast: 1, field: 1 },
  },
  fieldWraith: {
    name: "Feldschemen",
    sprite: "enemy-acolyte",
    level: 13,
    hp: 310,
    damage: [48, 70],
    defense: 23,
    xp: 210,
    gold: [22, 38],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "wraithLantern", chance: 0.022 }],
    elite: true,
    tags: { elite: 1, field: 1, dungeon: 1 },
  },
  ashMarauder: {
    name: "Aschenmarodeur",
    sprite: "enemy-bandit",
    level: 15,
    hp: 380,
    damage: [60, 86],
    defense: 29,
    xp: 260,
    gold: [30, 52],
    generatedLoot: { slots: ["weapon", "chest", "boots"], qualities: ["rare", "epic"] },
    drops: [{ id: "ashHook", chance: 0.022 }],
    tags: { bandit: 1, ash: 1 },
  },
  emberStalker: {
    name: "Glutpirscher",
    sprite: "enemy-wolf",
    level: 17,
    hp: 470,
    damage: [72, 105],
    defense: 34,
    xp: 355,
    gold: [40, 70],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberClaw", chance: 0.018 }],
    tags: { beast: 1, ash: 1 },
  },
  crownSentinel: {
    name: "Kronenwächter",
    sprite: "enemy-knight",
    level: 19,
    hp: 620,
    damage: [88, 126],
    defense: 43,
    xp: 520,
    gold: [52, 92],
    generatedLoot: { slots: ["offhand", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "sentinelVisor", chance: 0.016 }],
    elite: true,
    tags: { elite: 1, ash: 1 },
  },
  ratguard: {
    name: "Kellergardist",
    sprite: "enemy-ratguard",
    level: 9,
    hp: 190,
    damage: [32, 47],
    defense: 14,
    xp: 105,
    gold: [11, 22],
    generatedLoot: { slots: ["weapon", "offhand", "chest"], qualities: ["rare", "epic"] },
    drops: [{ id: "guardAxe", chance: 0.026 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  boneAcolyte: {
    name: "Knochenakolyth",
    sprite: "enemy-acolyte",
    level: 12,
    hp: 270,
    damage: [43, 64],
    defense: 20,
    xp: 170,
    gold: [17, 32],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "graveRing", chance: 0.024 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  cryptBrute: {
    name: "Gruftschläger",
    sprite: "enemy-brute",
    level: 15,
    hp: 390,
    damage: [62, 92],
    defense: 28,
    xp: 275,
    gold: [27, 48],
    generatedLoot: { slots: ["weapon", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "bruteMail", chance: 0.02 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  chainWarden: {
    name: "Kettenaufseher",
    sprite: "enemy-knight",
    level: 13,
    hp: 335,
    damage: [52, 76],
    defense: 28,
    xp: 240,
    gold: [26, 45],
    generatedLoot: { slots: ["offhand", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "wardenChain", chance: 0.024 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, bandit: 1 },
  },
  oathForger: {
    name: "Eidschmied",
    sprite: "enemy-brute",
    level: 16,
    hp: 500,
    damage: [70, 102],
    defense: 38,
    xp: 390,
    gold: [42, 76],
    generatedLoot: { slots: ["weapon", "offhand", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "forgeHammer", chance: 0.018 }, { id: "oathMantle", chance: 0.014 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  ironDuke: {
    name: "Herzog Eisenbruch",
    sprite: "enemy-knight",
    level: 18,
    hp: 610,
    damage: [82, 118],
    defense: 46,
    xp: 510,
    gold: [55, 98],
    generatedLoot: { slots: ["weapon", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "dukeSignet", chance: 0.016 }, { id: "ironCrownplate", chance: 0.012 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  emberPriest: {
    name: "Glutpriester",
    sprite: "enemy-acolyte",
    level: 18,
    hp: 540,
    damage: [84, 124],
    defense: 37,
    xp: 475,
    gold: [50, 90],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberRosary", chance: 0.018 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, ash: 1 },
  },
  crownBeast: {
    name: "Bestie der Krone",
    sprite: "enemy-boar",
    level: 19,
    hp: 720,
    damage: [92, 132],
    defense: 41,
    xp: 560,
    gold: [60, 105],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "crownFang", chance: 0.016 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, beast: 1, ash: 1 },
  },
  hollowChampion: {
    name: "Hohler Champion",
    sprite: "enemy-champion",
    level: 20,
    hp: 680,
    damage: [95, 138],
    defense: 44,
    xp: 620,
    gold: [58, 105],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "ashenGreatsword", chance: 0.012 }, { id: "crownShard", chance: 0.008 }],
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
};

const items = {
  trainingSword: { name: "Übungsschwert", slot: "weapon", quality: "common", damage: 4, defense: 0 },
  wornBuckler: { name: "Abgenutzter Buckler", slot: "offhand", quality: "common", damage: 0, defense: 2 },
  paddedVest: { name: "Gepolsterte Weste", slot: "chest", quality: "common", damage: 0, defense: 3 },
  patchedTrousers: { name: "Geflickte Hose", slot: "pants", quality: "common", damage: 0, defense: 2 },
  travelBoots: { name: "Reisestiefel", slot: "boots", quality: "common", damage: 0, defense: 1 },
  twineNecklace: { name: "Kordelhalskette", slot: "necklace", quality: "common", damage: 1, defense: 0 },
  copperRing: { name: "Kupferring", slot: "ring", quality: "common", damage: 1, defense: 1 },
  wolfRing: { name: "Ring des Rudels", slot: "ring", quality: "rare", damage: 2, defense: 2, set: "wolf" },
  rustBlade: { name: "Rostklinge", slot: "weapon", quality: "rare", damage: 8, defense: 0, set: "iron" },
  tollKnife: { name: "Zollmesser", slot: "weapon", quality: "rare", damage: 10, defense: 0, set: "iron" },
  houndGreaves: { name: "Eisenhund-Stiefel", slot: "boots", quality: "rare", damage: 2, defense: 8, set: "iron" },
  hideArmor: { name: "Dornenleder", slot: "chest", quality: "rare", damage: 0, defense: 9, set: "wolf" },
  oathRing: { name: "Eidring", slot: "ring", quality: "epic", damage: 4, defense: 4, set: "iron" },
  knightPlate: { name: "Grenzritterplatte", slot: "chest", quality: "epic", damage: 0, defense: 16, set: "iron" },
  crowTalisman: { name: "Seuchentalisman", slot: "necklace", quality: "epic", damage: 5, defense: 5, set: "crypt" },
  wraithLantern: { name: "Schemenlaterne", slot: "offhand", quality: "epic", damage: 5, defense: 12, set: "crypt" },
  ashHook: { name: "Aschenhaken", slot: "weapon", quality: "epic", damage: 18, defense: 0, set: "ashen" },
  emberClaw: { name: "Glutklaue", slot: "weapon", quality: "legendary", damage: 26, defense: 0, set: "ashen" },
  sentinelVisor: { name: "Kronenvisier", slot: "chest", quality: "legendary", damage: 3, defense: 42, set: "ashen" },
  guardAxe: { name: "Gardistenaxt", slot: "weapon", quality: "rare", damage: 12, defense: 0, set: "iron" },
  graveRing: { name: "Grablichtring", slot: "ring", quality: "epic", damage: 5, defense: 4, set: "crypt" },
  bruteMail: { name: "Schlägerkettenhemd", slot: "chest", quality: "epic", damage: 0, defense: 22, set: "crypt" },
  wardenChain: { name: "Kette des Aufsehers", slot: "offhand", quality: "epic", damage: 4, defense: 18, set: "iron" },
  forgeHammer: { name: "Hammer des Eidschmieds", slot: "weapon", quality: "legendary", damage: 30, defense: 0, set: "iron" },
  oathMantle: { name: "Eidmantel", slot: "chest", quality: "epic", damage: 1, defense: 28, set: "iron" },
  dukeSignet: { name: "Siegel des Herzogs", slot: "ring", quality: "legendary", damage: 9, defense: 10, set: "iron" },
  ironCrownplate: { name: "Eisenkronenplatte", slot: "chest", quality: "legendary", damage: 2, defense: 48, set: "iron" },
  emberRosary: { name: "Glutrosenkranz", slot: "necklace", quality: "legendary", damage: 12, defense: 9, set: "ashen" },
  crownFang: { name: "Kronenfang", slot: "weapon", quality: "legendary", damage: 34, defense: 0, set: "ashen" },
  ashenGreatsword: { name: "Aschgraues Großschwert", slot: "weapon", quality: "legendary", damage: 28, defense: 0, set: "ashen" },
  crownShard: { name: "Splitter der Krone", slot: "ring", quality: "legendary", damage: 8, defense: 8, set: "ashen" },
};

const qualityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  legendary: "Legendär",
};

const slotLabel = {
  weapon: "Waffe",
  offhand: "2. Hand",
  chest: "Brustpanzer",
  pants: "Hose",
  boots: "Stiefel",
  necklace: "Halskette",
  ring: "Ring",
};

const equipmentSlots = ["weapon", "offhand", "chest", "pants", "boots", "necklace", "ring"];
const lootSlots = [...equipmentSlots];

const qualityPower = {
  common: 1,
  rare: 1.28,
  epic: 1.62,
  legendary: 2.05,
};

const lootNames = {
  weapon: {
    common: ["Kerbenschwert", "Feldbeil", "Wachklinge"],
    rare: ["Runenklinge", "Blutrost-Axt", "Silberfalchion"],
    epic: ["Eidbrecher", "Sternstahlklinge", "Gruftspalter"],
    legendary: ["Königsschneide", "Aschenurteil", "Drachenzahn"],
  },
  offhand: {
    common: ["Holzschild", "Parierdolch", "Rostbuckler"],
    rare: ["Wolfsbuckler", "Gardistenschild", "Hakenklinge"],
    epic: ["Eidwall", "Runenfokus", "Gruftlaterne"],
    legendary: ["Sonnenschild", "Aschenfokus", "Splitterparade"],
  },
  chest: {
    common: ["Lederwams", "Kettenfetzen", "Reiserüstung"],
    rare: ["Wolfsleder", "Schildplattenrock", "Schuppenpanzer"],
    epic: ["Eidhüterplatte", "Nachtkettenhemd", "Runenharnisch"],
    legendary: ["Krone der Bastion", "Aschenpanzer", "Sonnenharnisch"],
  },
  pants: {
    common: ["Leinenhose", "Wanderbeinlinge", "Kettenhose"],
    rare: ["Wolfsbeinlinge", "Schmiedeplatten", "Räuberhose"],
    epic: ["Eidbeinplatten", "Grabstahl-Beinlinge", "Runenbeinpanzer"],
    legendary: ["Aschenbeinplatten", "Königsgamaschen", "Sonnenbeinschutz"],
  },
  boots: {
    common: ["Lederstiefel", "Marschschuhe", "Eisenkappen"],
    rare: ["Fährtenstiefel", "Wachstiefel", "Dornenläufer"],
    epic: ["Eidtreter", "Gruftschritte", "Runensohlen"],
    legendary: ["Aschenläufer", "Sonnenstiefel", "Kronenschritte"],
  },
  necklace: {
    common: ["Holzamulett", "Kordelkette", "Kupfertalisman"],
    rare: ["Wolfszahnkette", "Rostmedaillon", "Wachhalsreif"],
    epic: ["Eidamulett", "Grablichtkette", "Runenhalsreif"],
    legendary: ["Aschenmedaillon", "Sonnenanhänger", "Kronentalisman"],
  },
  ring: {
    common: ["Zinnring", "Feldreif", "Schlichter Talisman"],
    rare: ["Blutsteinring", "Wolfszeichen", "Wachtersiegel"],
    epic: ["Grablichtreif", "Eidsiegel", "Sternsplitterring"],
    legendary: ["Splitterkrone", "Ring des alten Feuers", "Königszeichen"],
  },
};

const setBonuses = {
  wolf: {
    name: "Rudeljäger",
    bonuses: {
      2: { damage: 3, defense: 1, text: "+3 Schaden, +1 Verteidigung" },
      4: { damage: 5, defense: 4, text: "+5 Schaden, +4 Verteidigung" },
      6: { damage: 11, defense: 7, maxHp: 18, text: "+11 Schaden, +7 Verteidigung, +18 Leben" },
    },
  },
  iron: {
    name: "Grenzwacht",
    bonuses: {
      2: { defense: 5, text: "+5 Verteidigung" },
      4: { damage: 3, defense: 10, text: "+3 Schaden, +10 Verteidigung" },
      6: { damage: 7, defense: 20, maxHp: 26, text: "+7 Schaden, +20 Verteidigung, +26 Leben" },
    },
  },
  crypt: {
    name: "Gruftbund",
    bonuses: {
      2: { damage: 4, maxHp: 12, text: "+4 Schaden, +12 Leben" },
      4: { damage: 7, defense: 6, maxHp: 22, text: "+7 Schaden, +6 Verteidigung, +22 Leben" },
      6: { damage: 13, defense: 11, maxHp: 48, text: "+13 Schaden, +11 Verteidigung, +48 Leben" },
    },
  },
  ashen: {
    name: "Aschenkrone",
    bonuses: {
      2: { damage: 8, defense: 5, text: "+8 Schaden, +5 Verteidigung" },
      4: { damage: 14, defense: 11, maxHp: 32, text: "+14 Schaden, +11 Verteidigung, +32 Leben" },
      6: { damage: 28, defense: 19, maxHp: 64, text: "+28 Schaden, +19 Verteidigung, +64 Leben" },
    },
  },
};

const questCatalog = [
  { id: "wolves", name: "Sichere den Waldrand", rarity: "common", text: "Töte 10 Waldwölfe.", target: "wolf", needed: 10, rewardXp: 70, rewardGold: 22 },
  { id: "rust", name: "Rost für den Schmied", rarity: "rare", text: "Sammle 5 Rostsplitter von Wegräubern.", target: "rust", needed: 5, rewardXp: 135, rewardGold: 44 },
  { id: "elites", name: "Mut unter Stein", rarity: "epic", text: "Besiege 3 Elite-Gegner.", target: "elite", needed: 3, rewardXp: 360, rewardGold: 95 },
  { id: "boars", name: "Dornen im Acker", rarity: "common", text: "Erlege 7 Dornenkeiler.", target: "beast", needed: 7, rewardXp: 190, rewardGold: 55 },
  { id: "dungeon", name: "Licht unter Stein", rarity: "epic", text: "Besiege 8 Dungeon-Gegner.", target: "dungeon", needed: 8, rewardXp: 330, rewardGold: 88 },
  { id: "bandits", name: "Wege wieder sicher", rarity: "rare", text: "Besiege 9 Wegräuber.", target: "bandit", needed: 9, rewardXp: 155, rewardGold: 50 },
  { id: "fields", name: "Nebel über den Feldern", rarity: "rare", text: "Vertreibe 6 Gegner aus den verfluchten Feldern.", target: "field", needed: 6, rewardXp: 260, rewardGold: 78 },
  { id: "ash", name: "Asche im Wind", rarity: "epic", text: "Besiege 6 Gegner im Aschengrund.", target: "ash", needed: 6, rewardXp: 520, rewardGold: 135 },
];

const rareQuestTemplates = [
  { key: "wolf", name: "Blutspur des Rudels", rarity: "legendary", text: "Jage 9 Waldwölfe für eine alte Jagdtrophaee.", target: "wolf", needed: 9, rewardXp: 260, rewardGold: 75, slot: "necklace" },
  { key: "bandit", name: "Versiegelter Steckbrief", rarity: "legendary", text: "Besiege 8 Wegräuber und bringe den Steckbrief zurück.", target: "bandit", needed: 8, rewardXp: 310, rewardGold: 95, slot: "weapon" },
  { key: "elite", name: "Schwur gegen die Gefallenen", rarity: "legendary", text: "Bezwinge 4 Elite-Gegner für eine seltene Reliquie.", target: "elite", needed: 4, rewardXp: 620, rewardGold: 150, slot: "chest" },
  { key: "dungeon", name: "Runen aus der Tiefe", rarity: "legendary", text: "Besiege 7 Dungeon-Gegner und berge eine Runenbelohnung.", target: "dungeon", needed: 7, rewardXp: 540, rewardGold: 130, slot: "ring" },
  { key: "ash", name: "Schwarzer Chor", rarity: "legendary", text: "Bezwinge 5 Aschengegner für eine versengte Reliquie.", target: "ash", needed: 5, rewardXp: 760, rewardGold: 190, slot: "necklace" },
];

const allQuestIds = () => [...questCatalog.map((quest) => quest.id), ...Object.keys(state?.rareQuests || {})];

const rarityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  legendary: "Legendär",
};

const materialLabel = {
  scrap: "Eisenstücke",
  leather: "Lederreste",
  cloth: "Stofffetzen",
  chain: "Kettenglieder",
  sinew: "Bestiensehnen",
  shard: "Runensplitter",
  moonDust: "Mondstaub",
  oathSteel: "Eidstahl",
  bone: "Knochenstücke",
  shadowResin: "Schattenharz",
  emberCore: "Glutkern",
  wolfFang: "Rudelfang",
  oathMark: "Eidmarke",
  graveSeal: "Grabessiegel",
  crownAsh: "Kronenasche",
};

const materialDrops = {
  wolf: [{ id: "leather", min: 1, max: 2 }, { id: "sinew", min: 0, max: 1 }],
  bandit: [{ id: "scrap", min: 1, max: 2 }, { id: "cloth", min: 0, max: 1 }],
  boar: [{ id: "leather", min: 2, max: 3 }, { id: "sinew", min: 1, max: 2 }],
  oldKnight: [{ id: "scrap", min: 2, max: 4 }, { id: "oathSteel", min: 0, max: 1 }],
  roadThief: [{ id: "scrap", min: 2, max: 3 }, { id: "cloth", min: 1, max: 2 }],
  ironHound: [{ id: "scrap", min: 2, max: 4 }, { id: "sinew", min: 1, max: 2 }],
  plagueCrow: [{ id: "bone", min: 1, max: 2 }, { id: "shadowResin", min: 0, max: 1 }],
  fieldWraith: [{ id: "shard", min: 1, max: 2 }, { id: "shadowResin", min: 1, max: 2 }],
  ashMarauder: [{ id: "scrap", min: 3, max: 5 }, { id: "emberCore", min: 0, max: 1 }],
  emberStalker: [{ id: "sinew", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }],
  crownSentinel: [{ id: "oathSteel", min: 2, max: 4 }, { id: "crownAsh", min: 1, max: 2 }],
  ratguard: [{ id: "scrap", min: 2, max: 3 }, { id: "chain", min: 0, max: 1 }],
  boneAcolyte: [{ id: "bone", min: 1, max: 3 }, { id: "shard", min: 1, max: 2 }],
  cryptBrute: [{ id: "chain", min: 2, max: 4 }, { id: "shadowResin", min: 0, max: 1 }],
  chainWarden: [{ id: "chain", min: 2, max: 4 }, { id: "oathSteel", min: 0, max: 1 }],
  oathForger: [{ id: "oathSteel", min: 2, max: 4 }, { id: "emberCore", min: 0, max: 1 }],
  ironDuke: [{ id: "oathSteel", min: 3, max: 5 }, { id: "oathMark", min: 1, max: 2 }],
  emberPriest: [{ id: "shard", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }],
  crownBeast: [{ id: "sinew", min: 3, max: 5 }, { id: "crownAsh", min: 1, max: 2 }],
  hollowChampion: [{ id: "oathSteel", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }, { id: "crownAsh", min: 0, max: 1 }],
};

