const saveKey = "fantasy-grind-save-v1";
const saveBackupKey = `${saveKey}-backup`;
const savePreviousKey = `${saveKey}-previous`;
const saveExportVersion = 1;

const xpForLevel = (level) => Math.floor(115 * Math.pow(level, 1.78) + level * 48);

const classCatalog = {
  warrior: {
    name: "Krieger",
    description: "Standhaft, direkt und stark mit Waffen.",
    abilities: ["battleRush", "shatter", "counterBlow"],
    buildAbilities: {
      tank: ["shieldWall", "tauntingBlow", "lastStand"],
      damage: ["heavyStrike", "bladeFlurry", "execute"],
      bruiser: ["battleRush", "shatter", "counterBlow"],
    },
  },
};

const buildCatalog = {
  tank: {
    name: "Tank",
    description: "Mehr Leben und Verteidigung. Schildwall ist stärker.",
    damageMultiplier: 0.92,
    defenseMultiplier: 1.18,
    maxHpMultiplier: 1.16,
    critChanceBonus: 0.01,
    critDamageBonus: 0.05,
    abilities: ["shieldWall", "tauntingBlow", "lastStand"],
  },
  damage: {
    name: "Schaden",
    description: "Mehr Schaden, aber etwas weniger Leben.",
    damageMultiplier: 1.16,
    defenseMultiplier: 0.94,
    maxHpMultiplier: 0.94,
    critChanceBonus: 0.06,
    critDamageBonus: 0.25,
    abilities: ["heavyStrike", "bladeFlurry", "execute"],
  },
  bruiser: {
    name: "Bruiser",
    description: "Ausgewogen. Kampfrausch heilt stärker.",
    damageMultiplier: 1.06,
    defenseMultiplier: 1.06,
    maxHpMultiplier: 1.04,
    critChanceBonus: 0.03,
    critDamageBonus: 0.1,
    abilities: ["battleRush", "shatter", "counterBlow"],
  },
};

const abilityCatalog = {
  heavyStrike: {
    name: "Schwerer Hieb",
    text: "Jede 3. Runde: 175% Schaden.",
  },
  bladeFlurry: {
    name: "Klingenserie",
    text: "Jede 4. Runde: ein zweiter Treffer mit 45% Schaden.",
  },
  execute: {
    name: "Hinrichten",
    text: "Unter 30% Gegnerleben: 150% Schaden, höchstens alle 2 Runden.",
  },
  shieldWall: {
    name: "Schildwall",
    text: "Jede 4. Runde: nächster Gegentreffer -55%.",
  },
  tauntingBlow: {
    name: "Spottender Schlag",
    text: "Jede 3. Runde: Angriff und gegnerischer Schaden -25%.",
  },
  lastStand: {
    name: "Letztes Aufbäumen",
    text: "Einmal unter 40% Leben: Heilung und kurze Schadensdämpfung.",
  },
  battleRush: {
    name: "Kampfrausch",
    text: "Einmal unter 45% Leben: heilt 18% Leben.",
  },
  shatter: {
    name: "Zerschmettern",
    text: "Jede 3. Runde: 130% Schaden und ein Teil der Rüstung wird ignoriert.",
  },
  counterBlow: {
    name: "Konterschlag",
    text: "Nach hartem Treffer: Konter mit 50% Schaden, höchstens alle 3 Runden.",
  },
};

const enemyAbilityCatalog = {
  bloodBite: { name: "Blutbiss", text: "Alle 3 Runden: Biss mit Blutung.", type: "active" },
  ambush: { name: "Hinterhalt", text: "Runde 1: deutlich stärkerer erster Treffer.", type: "active" },
  ironBite: { name: "Eisenbiss", text: "Alle 3 Runden: Biss, der deinen nächsten Schlag schwächt.", type: "active" },
  tuskCharge: { name: "Ansturm", text: "Alle 4 Runden: schwerer Treffer.", type: "active" },
  shieldBash: { name: "Schildstoß", text: "Alle 3 Runden: Schaden und dein nächster Angriff wird gedämpft.", type: "active" },
  guardStance: { name: "Schildhaltung", text: "Alle 4 Runden: nimmt deutlich weniger Schaden.", type: "active" },
  poisonClaws: { name: "Giftkrallen", text: "Alle 3 Runden: Gift über mehrere Runden.", type: "active" },
  lifeDrain: { name: "Lebensentzug", text: "Alle 4 Runden: Treffer heilt den Gegner.", type: "active" },
  mistForm: { name: "Nebelform", text: "Alle 4 Runden: dein Angriff wird stark gedämpft.", type: "active" },
  burningBlade: { name: "Brennende Klinge", text: "Alle 3 Runden: Treffer mit Brennen.", type: "active" },
  flameBite: { name: "Flammenbiss", text: "Alle 4 Runden: starker Treffer mit Brennen.", type: "active" },
  emberDodge: { name: "Glutausweichen", text: "Alle 3 Runden: dämpft deinen Treffer.", type: "active" },
  crownShield: { name: "Kronenschild", text: "Alle 4 Runden: reduziert eingehenden Schaden.", type: "active" },
  judgementStrike: { name: "Urteilsschlag", text: "Wenn du wenig Leben hast: gefährlicher Treffer.", type: "active" },
  guardBash: { name: "Wachhieb", text: "Alle 3 Runden: harter Kontrolltreffer.", type: "active" },
  chainHook: { name: "Kettenhaken", text: "Alle 4 Runden: zieht dich aus der Deckung und schwächt deinen Angriff.", type: "active" },
  boneCurse: { name: "Knochenfluch", text: "Alle 3 Runden: senkt deinen nächsten Schaden.", type: "active" },
  graveMend: { name: "Grabheilung", text: "Alle 4 Runden: heilt sich selbst.", type: "active" },
  crushingBlow: { name: "Zertrümmern", text: "Alle 4 Runden: sehr schwerer Treffer.", type: "active" },
  boneArmor: { name: "Knochenpanzer", text: "Alle 4 Runden: nimmt weniger Schaden.", type: "active" },
  forgeSmash: { name: "Amboss-Schlag", text: "Alle 3 Runden: massiver Hammerschlag.", type: "active" },
  emberChains: { name: "Glühende Ketten", text: "Alle 4 Runden: Schaden, Brennen und geschwächter Angriff.", type: "active" },
  hardenArmor: { name: "Rüstung härten", text: "Alle 4 Runden: reduziert deinen nächsten Treffer stark.", type: "active" },
  dukeCommand: { name: "Herzoglicher Befehl", text: "Alle 3 Runden: verstärkter Angriff.", type: "active" },
  ironWall: { name: "Eisenwand", text: "Alle 4 Runden: sehr starke Schadensreduktion.", type: "active" },
  executionOrder: { name: "Richtschlag", text: "Wenn du wenig Leben hast: extrem gefährlicher Treffer.", type: "active" },
  emberPrayer: { name: "Glutgebet", text: "Alle 4 Runden: leichter Treffer und Heilung.", type: "active" },
  ashNova: { name: "Aschennova", text: "Alle 5 Runden: Flächenschaden mit Brennen.", type: "active" },
  crownMaul: { name: "Kronenpranke", text: "Alle 4 Runden: brutaler Prankenhieb.", type: "active" },
  ashBlade: { name: "Aschenklinge", text: "Alle 3 Runden: Feuertreffer mit Brennen.", type: "active" },
  hollowGaze: { name: "Leerer Blick", text: "Alle 4 Runden: schwächt deinen nächsten Angriff.", type: "active" },
  championLeap: { name: "Champion-Sprung", text: "Alle 5 Runden: sehr schwerer Sprungangriff.", type: "active" },
  cellLockdown: { name: "Zellenschluss", text: "Alle 5 Runden: schwacher Treffer, aber dein nächster Angriff wird stark gedämpft.", type: "active" },
  graveTithe: { name: "Grabzehnt", text: "Alle 5 Runden: dunkler Treffer, der den Boss heilt.", type: "active" },
  bruteRampage: { name: "Gruftwut", text: "Unter 55% Leben: alle 3 Runden ein wuchtiger Treffer.", type: "active" },
  wardenVerdict: { name: "Aufseherurteil", text: "Alle 5 Runden: harter Kettenhieb und starke Angriffsschwächung.", type: "active" },
  anvilQuake: { name: "Ambossbeben", text: "Alle 5 Runden: schwerer Feuertreffer mit Brennen.", type: "active" },
  dukeDuel: { name: "Adelsduell", text: "Alle 5 Runden: präziser Hieb mit hoher Gefahr.", type: "active" },
  emberHymn: { name: "Gluthymne", text: "Alle 5 Runden: Feuer, Heilung und anhaltender Brand.", type: "active" },
  royalGore: { name: "Kronensturm", text: "Unter 60% Leben: alle 3 Runden ein brutaler Ansturm.", type: "active" },
  hollowRift: { name: "Leerenspalt", text: "Alle 5 Runden: Rissangriff, der deinen nächsten Schlag stark schwächt.", type: "active" },
  eliteFury: { name: "Elite-Wut", text: "Alle 4 Runden: zusätzlicher Elite-Druck.", type: "active" },
  eliteGuard: { name: "Elite-Deckung", text: "Alle 4 Runden: reduziert deinen Treffer.", type: "active" },
  prisonDiscipline: { name: "Kerkerdisziplin", text: "Passiv: jede 5. Runde weniger eingehender Schaden.", type: "passive" },
  lastGuard: { name: "Standhaft", text: "Passiv: unter 30% Leben nimmt der Gegner weniger Schaden.", type: "passive" },
  unholyRenewal: { name: "Unheilige Erneuerung", text: "Passiv: unter 50% Leben heilen Effekte stärker.", type: "passive" },
  heavyBody: { name: "Schwerer Körper", text: "Passiv: kleine Treffer werden gedämpft.", type: "passive" },
  forgeFire: { name: "Schmiedefeuer", text: "Passiv: unter 50% Leben verursacht der Gegner mehr Schaden.", type: "passive" },
  noblePride: { name: "Adelsstolz", text: "Passiv: unter 40% Leben wird der Herzog gefährlicher.", type: "passive" },
  royalHide: { name: "Kronenhaut", text: "Passiv: dauerhaft etwas weniger eingehender Schaden.", type: "passive" },
  secondPhase: { name: "Zweite Phase", text: "Passiv: unter 50% Leben stärker und zäher.", type: "passive" },
  cellAuthority: { name: "Kerkerautorität", text: "Passiv: die ersten Runden und jede fünfte Runde ist der Boss schwerer zu knacken.", type: "passive" },
  graveBargain: { name: "Grabpakt", text: "Passiv: unter 50% Leben wird Heilung stärker und der Boss zäher.", type: "passive" },
  bruteBulk: { name: "Massiger Leib", text: "Passiv: kleine Treffer prallen besonders stark ab.", type: "passive" },
  wardenPressure: { name: "Kettendruck", text: "Passiv: jede 4. Runde nimmt der Boss weniger Schaden.", type: "passive" },
  oathHeat: { name: "Eidglut", text: "Passiv: unter 50% Leben brennt der Boss härter und schlägt stärker.", type: "passive" },
  dukePride: { name: "Herzogsstolz", text: "Passiv: unter 45% Leben steigen Schaden und Widerstand.", type: "passive" },
  emberChoir: { name: "Glutchor", text: "Passiv: Heilungen sind stärker und Feuerdruck bleibt gefährlich.", type: "passive" },
  crownFrenzy: { name: "Kronenraserei", text: "Passiv: unter 55% Leben steigt der Schaden deutlich.", type: "passive" },
  hollowSecondWind: { name: "Leere Zweite Phase", text: "Passiv: unter 50% Leben wird der Champion stärker und zäher.", type: "passive" },
};

const zones = {
  meadow: {
    name: "Grauwacht-Wald",
    type: "zone",
    range: "Level 1-6",
    unlock: { level: 1, renown: 0 },
    enemies: ["wolf", "bandit", "boar"],
  },
  road: {
    name: "Räuberstraße",
    type: "zone",
    range: "Level 5-11",
    unlock: { level: 5, renown: 0 },
    enemies: ["roadThief", "ironHound", "oldKnight"],
  },
  fields: {
    name: "Verfluchte Felder",
    type: "zone",
    range: "Level 10-16",
    unlock: { level: 9, renown: 8 },
    enemies: ["plagueCrow", "fieldWraith", "oldKnight"],
  },
  ashgrounds: {
    name: "Aschengrund",
    type: "zone",
    range: "Level 15-20",
    unlock: { level: 14, renown: 20 },
    enemies: ["ashMarauder", "emberStalker", "crownSentinel"],
  },
  crypt: {
    name: "Krypta der Grauwacht",
    type: "dungeon",
    range: "Level 9-15",
    unlock: { level: 8, renown: 6 },
    enemies: ["ratguard", "boneAcolyte", "cryptBrute"],
  },
  ironhold: {
    name: "Eisenbruch-Festung",
    type: "dungeon",
    range: "Level 13-18",
    unlock: { level: 12, renown: 14 },
    enemies: ["chainWarden", "oathForger", "ironDuke"],
  },
  ashcathedral: {
    name: "Aschenkathedrale",
    type: "dungeon",
    range: "Level 18-20",
    unlock: { level: 17, renown: 30 },
    enemies: ["emberPriest", "crownBeast", "hollowChampion"],
  },
};

const enemies = {
  wolf: {
    name: "Waldwolf",
    sprite: "enemy-wolf",
    level: 1,
    hp: 44,
    damage: [7, 12],
    defense: 2,
    xp: 16,
    gold: [2, 4],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["common", "rare"] },
    drops: [{ id: "wolfRing", chance: 0.024 }],
    abilities: ["bloodBite"],
    tags: { wolf: 1 },
  },
  bandit: {
    name: "Wegräuber",
    sprite: "enemy-bandit",
    level: 3,
    hp: 72,
    damage: [12, 19],
    defense: 5,
    xp: 30,
    gold: [4, 9],
    generatedLoot: { slots: ["weapon", "offhand", "necklace"], qualities: ["common", "rare"] },
    drops: [{ id: "rustBlade", chance: 0.038 }],
    abilities: ["ambush"],
    tags: { bandit: 1, rust: 0.32 },
  },
  roadThief: {
    name: "Straßenräuber",
    sprite: "enemy-bandit",
    level: 5,
    hp: 108,
    damage: [18, 28],
    defense: 8,
    xp: 52,
    gold: [8, 15],
    generatedLoot: { slots: ["weapon", "offhand", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "tollKnife", chance: 0.034 }],
    abilities: ["ambush"],
    tags: { bandit: 1, rust: 0.45 },
  },
  ironHound: {
    name: "Eisenhund",
    sprite: "enemy-wolf",
    level: 8,
    hp: 168,
    damage: [27, 39],
    defense: 13,
    xp: 86,
    gold: [10, 19],
    generatedLoot: { slots: ["chest", "boots", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "houndGreaves", chance: 0.026 }],
    abilities: ["ironBite"],
    tags: { beast: 1, rust: 0.25 },
  },
  boar: {
    name: "Dornenkeiler",
    sprite: "enemy-boar",
    level: 6,
    hp: 122,
    damage: [20, 31],
    defense: 8,
    xp: 62,
    gold: [7, 13],
    generatedLoot: { slots: ["chest", "pants", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "hideArmor", chance: 0.032 }],
    abilities: ["tuskCharge"],
    tags: { beast: 1 },
  },
  oldKnight: {
    name: "Alter Grenzritter",
    sprite: "enemy-knight",
    level: 10,
    hp: 210,
    damage: [34, 50],
    defense: 17,
    xp: 120,
    gold: [14, 25],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "oathRing", chance: 0.018 }, { id: "knightPlate", chance: 0.012 }],
    abilities: ["shieldBash", "guardStance"],
    passives: ["lastGuard"],
    elite: true,
    tags: { elite: 1 },
  },
  plagueCrow: {
    name: "Seuchenkrähe",
    sprite: "enemy-acolyte",
    level: 10,
    hp: 205,
    damage: [35, 52],
    defense: 15,
    xp: 128,
    gold: [15, 27],
    generatedLoot: { slots: ["necklace", "ring", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "crowTalisman", chance: 0.024 }],
    abilities: ["poisonClaws"],
    tags: { beast: 1, field: 1 },
  },
  fieldWraith: {
    name: "Feldschemen",
    sprite: "enemy-acolyte",
    level: 13,
    hp: 310,
    damage: [48, 70],
    defense: 23,
    xp: 210,
    gold: [22, 38],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "wraithLantern", chance: 0.022 }],
    abilities: ["lifeDrain", "mistForm"],
    elite: true,
    tags: { elite: 1, field: 1, dungeon: 1 },
  },
  ashMarauder: {
    name: "Aschenmarodeur",
    sprite: "enemy-bandit",
    level: 15,
    hp: 380,
    damage: [60, 86],
    defense: 29,
    xp: 260,
    gold: [30, 52],
    generatedLoot: { slots: ["weapon", "chest", "boots"], qualities: ["rare", "epic"] },
    drops: [{ id: "ashHook", chance: 0.022 }],
    abilities: ["burningBlade"],
    tags: { bandit: 1, ash: 1 },
  },
  emberStalker: {
    name: "Glutpirscher",
    sprite: "enemy-wolf",
    level: 17,
    hp: 470,
    damage: [72, 105],
    defense: 34,
    xp: 355,
    gold: [40, 70],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberClaw", chance: 0.018 }],
    abilities: ["flameBite", "emberDodge"],
    tags: { beast: 1, ash: 1 },
  },
  crownSentinel: {
    name: "Kronenwächter",
    sprite: "enemy-knight",
    level: 19,
    hp: 620,
    damage: [88, 126],
    defense: 43,
    xp: 520,
    gold: [52, 92],
    generatedLoot: { slots: ["offhand", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "sentinelVisor", chance: 0.016 }],
    abilities: ["crownShield", "judgementStrike", "shieldBash"],
    passives: ["lastGuard"],
    elite: true,
    tags: { elite: 1, ash: 1 },
  },
  ratguard: {
    name: "Kellergardist",
    sprite: "enemy-ratguard",
    level: 9,
    hp: 190,
    damage: [32, 47],
    defense: 14,
    xp: 105,
    gold: [11, 22],
    generatedLoot: { slots: ["weapon", "offhand", "chest"], qualities: ["rare", "epic"] },
    drops: [{ id: "guardAxe", chance: 0.055 }, { id: "cellkeeperBulwark", chance: 0.04 }],
    abilities: ["guardBash", "guardStance", "chainHook", "cellLockdown"],
    passives: ["prisonDiscipline", "cellAuthority"],
    firstClear: { renown: 2, gold: 85, materials: { chain: 2, scrap: 4 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  boneAcolyte: {
    name: "Knochenakolyth",
    sprite: "enemy-acolyte",
    level: 12,
    hp: 270,
    damage: [43, 64],
    defense: 20,
    xp: 170,
    gold: [17, 32],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "graveRing", chance: 0.05 }, { id: "boneChalice", chance: 0.036 }],
    abilities: ["boneCurse", "graveMend", "lifeDrain", "graveTithe"],
    passives: ["unholyRenewal", "graveBargain"],
    firstClear: { renown: 2, gold: 125, materials: { bone: 5, graveSeal: 1 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  cryptBrute: {
    name: "Gruftschläger",
    sprite: "enemy-brute",
    level: 15,
    hp: 390,
    damage: [62, 92],
    defense: 28,
    xp: 275,
    gold: [27, 48],
    generatedLoot: { slots: ["weapon", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "bruteMail", chance: 0.042 }, { id: "cryptCrusher", chance: 0.032 }],
    abilities: ["crushingBlow", "boneArmor", "tuskCharge", "bruteRampage"],
    passives: ["heavyBody", "bruteBulk"],
    firstClear: { renown: 3, gold: 180, materials: { chain: 4, shadowResin: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  chainWarden: {
    name: "Kettenaufseher",
    sprite: "enemy-knight",
    level: 13,
    hp: 335,
    damage: [52, 76],
    defense: 28,
    xp: 240,
    gold: [26, 45],
    generatedLoot: { slots: ["offhand", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "wardenChain", chance: 0.045 }, { id: "wardenShackle", chance: 0.034 }],
    abilities: ["chainHook", "guardStance", "shieldBash", "wardenVerdict"],
    passives: ["prisonDiscipline", "wardenPressure"],
    firstClear: { renown: 3, gold: 210, materials: { chain: 5, oathSteel: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, bandit: 1 },
  },
  oathForger: {
    name: "Eidschmied",
    sprite: "enemy-brute",
    level: 16,
    hp: 500,
    damage: [70, 102],
    defense: 38,
    xp: 390,
    gold: [42, 76],
    generatedLoot: { slots: ["weapon", "offhand", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "forgeHammer", chance: 0.035 }, { id: "oathMantle", chance: 0.028 }],
    abilities: ["forgeSmash", "emberChains", "hardenArmor", "anvilQuake"],
    passives: ["forgeFire", "oathHeat"],
    firstClear: { renown: 4, gold: 285, materials: { oathSteel: 4, emberCore: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  ironDuke: {
    name: "Herzog Eisenbruch",
    sprite: "enemy-knight",
    level: 18,
    hp: 610,
    damage: [82, 118],
    defense: 46,
    xp: 510,
    gold: [55, 98],
    generatedLoot: { slots: ["weapon", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "dukeSignet", chance: 0.032 }, { id: "ironCrownplate", chance: 0.026 }],
    abilities: ["dukeCommand", "ironWall", "executionOrder", "dukeDuel"],
    passives: ["noblePride", "dukePride"],
    firstClear: { renown: 4, gold: 360, materials: { oathMark: 2, oathSteel: 5 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  emberPriest: {
    name: "Glutpriester",
    sprite: "enemy-acolyte",
    level: 18,
    hp: 540,
    damage: [84, 124],
    defense: 37,
    xp: 475,
    gold: [50, 90],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberRosary", chance: 0.032 }, { id: "emberCenser", chance: 0.026 }],
    abilities: ["emberHymn", "emberPrayer", "ashNova", "graveMend"],
    passives: ["forgeFire", "emberChoir"],
    firstClear: { renown: 4, gold: 380, materials: { shard: 6, emberCore: 3 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, ash: 1 },
  },
  crownBeast: {
    name: "Bestie der Krone",
    sprite: "enemy-boar",
    level: 19,
    hp: 720,
    damage: [92, 132],
    defense: 41,
    xp: 560,
    gold: [60, 105],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "crownFang", chance: 0.03 }, { id: "royalSpurs", chance: 0.024 }],
    abilities: ["crownMaul", "tuskCharge", "judgementStrike", "royalGore"],
    passives: ["royalHide", "crownFrenzy"],
    firstClear: { renown: 5, gold: 430, materials: { sinew: 6, crownAsh: 3 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, beast: 1, ash: 1 },
  },
  hollowChampion: {
    name: "Hohler Champion",
    sprite: "enemy-champion",
    level: 20,
    hp: 680,
    damage: [95, 138],
    defense: 44,
    xp: 620,
    gold: [58, 105],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "ashenGreatsword", chance: 0.028 }, { id: "crownShard", chance: 0.018 }],
    abilities: ["hollowRift", "ashBlade", "hollowGaze", "championLeap"],
    passives: ["secondPhase", "hollowSecondWind"],
    firstClear: { renown: 6, gold: 520, materials: { crownAsh: 4, emberCore: 3, graveSeal: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
};

const items = {
  trainingSword: { name: "Übungsschwert", slot: "weapon", quality: "common", damage: 4, defense: 0, critChance: 0.01 },
  wornBuckler: { name: "Abgenutzter Buckler", slot: "offhand", quality: "common", damage: 0, defense: 2 },
  paddedVest: { name: "Gepolsterte Weste", slot: "chest", quality: "common", damage: 0, defense: 3 },
  patchedTrousers: { name: "Geflickte Hose", slot: "pants", quality: "common", damage: 0, defense: 2 },
  travelBoots: { name: "Reisestiefel", slot: "boots", quality: "common", damage: 0, defense: 1 },
  twineNecklace: { name: "Kordelhalskette", slot: "necklace", quality: "common", damage: 1, defense: 0, critDamage: 0.04 },
  copperRing: { name: "Kupferring", slot: "ring", quality: "common", damage: 2, defense: 0, critChance: 0.01 },
  wolfRing: { name: "Ring des Rudels", slot: "ring", quality: "rare", damage: 3, defense: 0, critChance: 0.03, set: "wolf", effect: "eliteHunter" },
  rustBlade: { name: "Rostklinge", slot: "weapon", quality: "rare", damage: 8, defense: 0, critChance: 0.03, set: "iron", effect: "bleedEdge" },
  tollKnife: { name: "Zollmesser", slot: "weapon", quality: "rare", damage: 10, defense: 0, critChance: 0.04, critDamage: 0.08, set: "iron", effect: "bleedEdge" },
  houndGreaves: { name: "Eisenhund-Stiefel", slot: "boots", quality: "rare", damage: 0, defense: 10, set: "iron", effect: "steadyStep" },
  hideArmor: { name: "Dornenleder", slot: "chest", quality: "rare", damage: 0, defense: 9, set: "wolf", effect: "thornGuard" },
  oathRing: { name: "Eidring", slot: "ring", quality: "epic", damage: 4, defense: 4, critChance: 0.04, set: "iron", effect: "eliteHunter" },
  knightPlate: { name: "Grenzritterplatte", slot: "chest", quality: "epic", damage: 0, defense: 16, set: "iron", effect: "steadfastWard" },
  crowTalisman: { name: "Seuchentalisman", slot: "necklace", quality: "epic", damage: 8, defense: 0, critDamage: 0.16, set: "crypt", effect: "graveCurse" },
  wraithLantern: { name: "Schemenlaterne", slot: "offhand", quality: "epic", damage: 5, defense: 14, set: "crypt", effect: "graveCurse" },
  ashHook: { name: "Aschenhaken", slot: "weapon", quality: "epic", damage: 18, defense: 0, critChance: 0.05, critDamage: 0.12, set: "ashen", effect: "crownBurn" },
  emberClaw: { name: "Glutklaue", slot: "weapon", quality: "legendary", damage: 26, defense: 0, critChance: 0.08, critDamage: 0.22, set: "ashen", effect: "crownBurn" },
  sentinelVisor: { name: "Kronenvisier", slot: "chest", quality: "legendary", damage: 0, defense: 46, set: "ashen", effect: "steadfastWard" },
  guardAxe: { name: "Gardistenaxt", slot: "weapon", quality: "rare", damage: 12, defense: 0, set: "iron", effect: "bleedEdge" },
  cellkeeperBulwark: { name: "Bollwerk des Zellhüters", slot: "offhand", quality: "epic", damage: 3, defense: 17, set: "iron", effect: "cellLock" },
  graveRing: { name: "Grablichtring", slot: "ring", quality: "epic", damage: 8, defense: 0, critChance: 0.04, critDamage: 0.08, set: "crypt", effect: "graveCurse" },
  boneChalice: { name: "Kelch der stillen Knochen", slot: "necklace", quality: "epic", damage: 7, defense: 0, critDamage: 0.14, set: "crypt", effect: "boneLeech" },
  bruteMail: { name: "Schlägerkettenhemd", slot: "chest", quality: "epic", damage: 0, defense: 22, set: "crypt", effect: "bruteThorns" },
  cryptCrusher: { name: "Gruftspalter", slot: "weapon", quality: "epic", damage: 23, defense: 0, critChance: 0.04, critDamage: 0.14, set: "crypt", effect: "breakerMark" },
  wardenChain: { name: "Kette des Aufsehers", slot: "offhand", quality: "epic", damage: 4, defense: 18, set: "iron", effect: "guardBlock" },
  wardenShackle: { name: "Aufseherfessel", slot: "ring", quality: "epic", damage: 7, defense: 0, critChance: 0.03, set: "iron", effect: "chainSnare" },
  forgeHammer: { name: "Hammer des Eidschmieds", slot: "weapon", quality: "legendary", damage: 30, defense: 0, critDamage: 0.34, set: "iron", effect: "oathBreaker" },
  oathMantle: { name: "Eidmantel", slot: "chest", quality: "epic", damage: 0, defense: 30, set: "iron", effect: "steadfastWard" },
  dukeSignet: { name: "Siegel des Herzogs", slot: "ring", quality: "legendary", damage: 15, defense: 0, critChance: 0.06, critDamage: 0.12, set: "iron", effect: "eliteHunter" },
  ironCrownplate: { name: "Eisenkronenplatte", slot: "chest", quality: "legendary", damage: 0, defense: 52, set: "iron", effect: "steadfastWard" },
  emberRosary: { name: "Glutrosenkranz", slot: "necklace", quality: "legendary", damage: 18, defense: 0, critDamage: 0.28, set: "ashen", effect: "echoHeal" },
  emberCenser: { name: "Rauchfass der Glutmesse", slot: "offhand", quality: "legendary", damage: 7, defense: 32, set: "ashen", effect: "emberWard" },
  crownFang: { name: "Kronenfang", slot: "weapon", quality: "legendary", damage: 34, defense: 0, critChance: 0.07, critDamage: 0.24, set: "ashen", effect: "lifeSiphon" },
  royalSpurs: { name: "Königssporn", slot: "boots", quality: "legendary", damage: 0, defense: 28, set: "ashen", effect: "royalPace" },
  ashenGreatsword: { name: "Aschgraues Großschwert", slot: "weapon", quality: "legendary", damage: 28, defense: 0, critChance: 0.04, critDamage: 0.32, set: "ashen", effect: "crownBurn" },
  crownShard: { name: "Splitter der Krone", slot: "ring", quality: "legendary", damage: 14, defense: 0, critChance: 0.05, critDamage: 0.18, set: "ashen", effect: "duelistMark" },
};

const itemEffectCatalog = {
  bleedEdge: {
    name: "Blutkante",
    text: "Treffer haben 8% Chance auf Blutung für 2 Runden.",
    slots: ["weapon"],
    bleedChance: 0.08,
  },
  venomEdge: {
    name: "Giftkante",
    text: "Treffer haben 10% Chance auf Gift für 3 Runden.",
    slots: ["weapon"],
    poisonChance: 0.1,
  },
  guardBlock: {
    name: "Wachblock",
    text: "Der erste Gegentreffer im Kampf wird um 15% reduziert.",
    slots: ["offhand", "chest"],
    firstHitReduction: 0.15,
  },
  cellLock: {
    name: "Zellenschloss",
    text: "Der erste Gegentreffer wird um 12% reduziert und der Konter geschwächt.",
    slots: ["offhand"],
    firstHitReduction: 0.12,
    firstHitWeaken: 0.9,
  },
  thornGuard: {
    name: "Dornenwache",
    text: "Gegentreffer werfen 8% Schaden auf den Gegner zurück.",
    slots: ["offhand", "chest", "pants"],
    thornsRatio: 0.08,
  },
  bruteThorns: {
    name: "Gruftdornen",
    text: "Gegentreffer werfen 10% Schaden auf den Gegner zurück.",
    slots: ["chest", "pants"],
    thornsRatio: 0.1,
  },
  steadfastWard: {
    name: "Standfeste Rune",
    text: "Gegnerische Crit-Chance -3%.",
    slots: ["offhand", "chest", "pants"],
    enemyCritReduction: 0.03,
  },
  steadyStep: {
    name: "Zäher Schritt",
    text: "Haltbarkeitsverlust nach Kämpfen -10%.",
    slots: ["pants", "boots"],
    durabilityReduction: 0.1,
  },
  luckyPouch: {
    name: "Glückstasche",
    text: "Nach Siegen +8% Gold.",
    slots: ["boots", "ring", "necklace"],
    goldBonus: 0.08,
  },
  royalPace: {
    name: "Königsschritt",
    text: "Haltbarkeitsverlust -10% und nach Siegen +8% Gold.",
    slots: ["boots"],
    durabilityReduction: 0.1,
    goldBonus: 0.08,
  },
  eliteHunter: {
    name: "Elitenjäger",
    text: "+6% Crit-Chance gegen Elite-Gegner und Bosse.",
    slots: ["ring", "necklace"],
    eliteCritChance: 0.06,
  },
  duelistMark: {
    name: "Duellzeichen",
    text: "+10% Schaden gegen Elite-Gegner und Bosse.",
    slots: ["weapon", "ring", "necklace"],
    eliteDamageBonus: 0.1,
  },
  breakerMark: {
    name: "Brecherzeichen",
    text: "+8% Schaden und 12% Rüstungsbruch gegen Elite-Gegner und Bosse.",
    slots: ["weapon"],
    eliteDamageBonus: 0.08,
    eliteArmorIgnore: 0.12,
  },
  echoHeal: {
    name: "Nachhall",
    text: "Nach einem Sieg heilt 4% Leben.",
    slots: ["ring", "necklace"],
    postCombatHeal: 0.04,
  },
  boneLeech: {
    name: "Knochenzehrung",
    text: "Kritische Treffer heilen 2% Leben. Nach einem Sieg heilt 3% Leben.",
    slots: ["ring", "necklace"],
    critHealRatio: 0.02,
    postCombatHeal: 0.03,
  },
  lifeSiphon: {
    name: "Lebenssog",
    text: "Kritische Treffer heilen 3% Leben.",
    slots: ["weapon", "ring", "necklace"],
    critHealRatio: 0.03,
  },
  emberWard: {
    name: "Glutweihe",
    text: "Der erste Gegentreffer wird um 12% reduziert. Nach einem Sieg heilt 3% Leben.",
    slots: ["offhand", "necklace"],
    firstHitReduction: 0.12,
    postCombatHeal: 0.03,
  },
  crownBurn: {
    name: "Kronenbrand",
    text: "Kritische Treffer verursachen Brennen für 2 Runden.",
    slots: ["weapon", "ring", "necklace"],
    critBurn: true,
  },
  oathBreaker: {
    name: "Eidbrecher",
    text: "Treffer gegen Elite-Gegner und Bosse ignorieren 18% Rüstung.",
    slots: ["weapon", "offhand"],
    eliteArmorIgnore: 0.18,
  },
  graveCurse: {
    name: "Grabfluch",
    text: "Der erste Treffer schwächt den nächsten Gegenschlag.",
    slots: ["offhand", "ring", "necklace"],
    firstHitWeaken: 0.88,
  },
  chainSnare: {
    name: "Kettenfang",
    text: "Der erste Treffer schwächt den nächsten Gegenschlag stark.",
    slots: ["ring", "offhand"],
    firstHitWeaken: 0.82,
  },
};

const enchantmentCatalog = {
  keenEdge: {
    name: "Scharfe Rune",
    category: "offense",
    rarity: "common",
    group: "critChance",
    slots: ["weapon", "ring", "necklace"],
    stats: { critChance: 0.02 },
    text: "+2% Crit-Chance",
  },
  emberStrike: {
    name: "Glutfunke",
    category: "offense",
    rarity: "common",
    group: "damage",
    slots: ["weapon", "offhand", "ring", "necklace"],
    stats: { damage: 2 },
    text: "+2 Angriff",
  },
  cruelMark: {
    name: "Grausames Zeichen",
    category: "offense",
    rarity: "rare",
    group: "critDamage",
    slots: ["weapon", "ring", "necklace"],
    stats: { critDamage: 0.08 },
    text: "+8% Crit-Schaden",
  },
  bossOath: {
    name: "Boss-Schwur",
    category: "offense",
    rarity: "rare",
    group: "bossDamage",
    slots: ["weapon", "offhand", "ring", "necklace"],
    stats: { bossDamage: 0.06 },
    text: "+6% Schaden gegen Elite und Bosse",
  },
  runicGuard: {
    name: "Wachrune",
    category: "defense",
    rarity: "common",
    group: "defense",
    slots: ["offhand", "chest", "pants", "boots"],
    stats: { defense: 3 },
    text: "+3 Verteidigung",
  },
  lifeThread: {
    name: "Lebensfaden",
    category: "defense",
    rarity: "common",
    group: "maxHp",
    slots: ["chest", "pants", "boots", "necklace", "ring"],
    stats: { maxHp: 14 },
    text: "+14 Leben",
  },
  ironSkin: {
    name: "Eisenhaut",
    category: "defense",
    rarity: "rare",
    group: "damageReduction",
    slots: ["offhand", "chest", "pants"],
    stats: { damageReduction: 0.04 },
    text: "-4% erlittener Schaden",
  },
  wardSpark: {
    name: "Schutzfunke",
    category: "defense",
    rarity: "rare",
    group: "lowHpShield",
    slots: ["chest", "offhand", "necklace"],
    stats: { lowHpShield: 0.08 },
    text: "Unter 35% Leben zählt dein Leben im Risiko höher",
  },
  coinWhisper: {
    name: "Münzflüstern",
    category: "utility",
    rarity: "common",
    group: "goldBonus",
    slots: ["boots", "necklace", "ring"],
    stats: { goldBonus: 0.08 },
    text: "+8% Gold aus Kämpfen",
  },
  scholarDust: {
    name: "Gelehrtenstaub",
    category: "utility",
    rarity: "common",
    group: "xpBonus",
    slots: ["necklace", "ring", "boots"],
    stats: { xpBonus: 0.06 },
    text: "+6% XP aus Kämpfen",
  },
  scavengerRune: {
    name: "Sucherrune",
    category: "utility",
    rarity: "rare",
    group: "lootBonus",
    slots: ["boots", "necklace", "ring"],
    stats: { lootBonus: 0.05 },
    text: "+5% Chance auf bessere Beute",
  },
  menderMark: {
    name: "Pflegezeichen",
    category: "utility",
    rarity: "rare",
    group: "durabilityReduction",
    slots: ["weapon", "offhand", "chest", "pants", "boots"],
    stats: { durabilityReduction: 0.08 },
    text: "-8% Haltbarkeitsverlust",
  },
  warSigil: {
    name: "Kriegssiegel",
    category: "offense",
    rarity: "epic",
    group: "damage",
    slots: ["weapon", "ring", "necklace"],
    stats: { damage: 5, critChance: 0.02 },
    text: "+5 Angriff und +2% Crit-Chance",
  },
  bastionGlyph: {
    name: "Bastionsglyphe",
    category: "defense",
    rarity: "epic",
    group: "damageReduction",
    slots: ["offhand", "chest", "pants"],
    stats: { defense: 5, damageReduction: 0.05 },
    text: "+5 Verteidigung und -5% erlittener Schaden",
  },
  luckyStar: {
    name: "Glücksstern",
    category: "utility",
    rarity: "epic",
    group: "lootBonus",
    slots: ["necklace", "ring"],
    stats: { lootBonus: 0.09, goldBonus: 0.08 },
    text: "+9% bessere Beute und +8% Gold",
  },
  voidEdge: {
    name: "Leerenkante",
    category: "offense",
    rarity: "arcane",
    group: "arcaneDamage",
    slots: ["weapon", "ring", "necklace"],
    stats: { damage: 10, critChance: 0.04, defense: -3 },
    text: "+10 Angriff, +4% Crit-Chance, aber -3 Verteidigung",
  },
  starBulwark: {
    name: "Sternenbann",
    category: "defense",
    rarity: "arcane",
    group: "arcaneShield",
    slots: ["offhand", "chest", "pants"],
    stats: { maxHp: 80, damageReduction: 0.07, critDamage: -0.08 },
    text: "+80 Leben und -7% erlittener Schaden, aber -8% Crit-Schaden",
  },
  fateThread: {
    name: "Schicksalsfaden",
    category: "utility",
    rarity: "arcane",
    group: "arcaneFortune",
    slots: ["boots", "necklace", "ring"],
    stats: { lootBonus: 0.12, xpBonus: 0.12, goldBonus: 0.12, maxHp: -25 },
    text: "+12% Beute, XP und Gold, aber -25 Leben",
  },
};

const enchantmentCategoryLabel = {
  offense: "Offensiv",
  defense: "Defensiv",
  utility: "Utility",
};

const enchantmentRarityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  arcane: "Arkan",
};

const qualityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  legendary: "Legendär",
};

const slotLabel = {
  weapon: "Waffe",
  offhand: "2. Hand",
  chest: "Brustpanzer",
  pants: "Hose",
  boots: "Stiefel",
  necklace: "Halskette",
  ring: "Ring",
};

const equipmentSlots = ["weapon", "offhand", "chest", "pants", "boots", "necklace", "ring"];
const lootSlots = [...equipmentSlots];

const qualityPower = {
  common: 1,
  rare: 1.28,
  epic: 1.62,
  legendary: 2.05,
};

const lootNames = {
  weapon: {
    common: ["Kerbenschwert", "Feldbeil", "Wachklinge"],
    rare: ["Runenklinge", "Blutrost-Axt", "Silberfalchion"],
    epic: ["Eidbrecher", "Sternstahlklinge", "Gruftspalter"],
    legendary: ["Königsschneide", "Aschenurteil", "Drachenzahn"],
  },
  offhand: {
    common: ["Holzschild", "Parierdolch", "Rostbuckler"],
    rare: ["Wolfsbuckler", "Gardistenschild", "Hakenklinge"],
    epic: ["Eidwall", "Runenfokus", "Gruftlaterne"],
    legendary: ["Sonnenschild", "Aschenfokus", "Splitterparade"],
  },
  chest: {
    common: ["Lederwams", "Kettenfetzen", "Reiserüstung"],
    rare: ["Wolfsleder", "Schildplattenrock", "Schuppenpanzer"],
    epic: ["Eidhüterplatte", "Nachtkettenhemd", "Runenharnisch"],
    legendary: ["Krone der Bastion", "Aschenpanzer", "Sonnenharnisch"],
  },
  pants: {
    common: ["Leinenhose", "Wanderbeinlinge", "Kettenhose"],
    rare: ["Wolfsbeinlinge", "Schmiedeplatten", "Räuberhose"],
    epic: ["Eidbeinplatten", "Grabstahl-Beinlinge", "Runenbeinpanzer"],
    legendary: ["Aschenbeinplatten", "Königsgamaschen", "Sonnenbeinschutz"],
  },
  boots: {
    common: ["Lederstiefel", "Marschschuhe", "Eisenkappen"],
    rare: ["Fährtenstiefel", "Wachstiefel", "Dornenläufer"],
    epic: ["Eidtreter", "Gruftschritte", "Runensohlen"],
    legendary: ["Aschenläufer", "Sonnenstiefel", "Kronenschritte"],
  },
  necklace: {
    common: ["Holzamulett", "Kordelkette", "Kupfertalisman"],
    rare: ["Wolfszahnkette", "Rostmedaillon", "Wachhalsreif"],
    epic: ["Eidamulett", "Grablichtkette", "Runenhalsreif"],
    legendary: ["Aschenmedaillon", "Sonnenanhänger", "Kronentalisman"],
  },
  ring: {
    common: ["Zinnring", "Feldreif", "Schlichter Talisman"],
    rare: ["Blutsteinring", "Wolfszeichen", "Wachtersiegel"],
    epic: ["Grablichtreif", "Eidsiegel", "Sternsplitterring"],
    legendary: ["Splitterkrone", "Ring des alten Feuers", "Königszeichen"],
  },
};

const setBonuses = {
  wolf: {
    name: "Rudeljäger",
    bonuses: {
      2: { damage: 3, defense: 1, text: "+3 Schaden, +1 Verteidigung" },
      4: { damage: 5, defense: 4, text: "+5 Schaden, +4 Verteidigung" },
      6: { damage: 11, defense: 7, maxHp: 18, text: "+11 Schaden, +7 Verteidigung, +18 Leben" },
    },
  },
  iron: {
    name: "Grenzwacht",
    bonuses: {
      2: { defense: 5, text: "+5 Verteidigung" },
      4: { damage: 3, defense: 10, text: "+3 Schaden, +10 Verteidigung" },
      6: { damage: 7, defense: 20, maxHp: 26, text: "+7 Schaden, +20 Verteidigung, +26 Leben" },
    },
  },
  crypt: {
    name: "Gruftbund",
    bonuses: {
      2: { damage: 4, maxHp: 12, text: "+4 Schaden, +12 Leben" },
      4: { damage: 7, defense: 6, maxHp: 22, text: "+7 Schaden, +6 Verteidigung, +22 Leben" },
      6: { damage: 13, defense: 11, maxHp: 48, text: "+13 Schaden, +11 Verteidigung, +48 Leben" },
    },
  },
  ashen: {
    name: "Aschenkrone",
    bonuses: {
      2: { damage: 8, defense: 5, text: "+8 Schaden, +5 Verteidigung" },
      4: { damage: 14, defense: 11, maxHp: 32, text: "+14 Schaden, +11 Verteidigung, +32 Leben" },
      6: { damage: 28, defense: 19, maxHp: 64, text: "+28 Schaden, +19 Verteidigung, +64 Leben" },
    },
  },
};

const questCatalog = [
  { id: "wolves", name: "Sichere den Waldrand", rarity: "common", repeatable: true, text: "Töte 10 Waldwölfe.", target: "wolf", needed: 10, rewardXp: 70, rewardGold: 22 },
  { id: "rust", name: "Rost für den Schmied", rarity: "rare", repeatable: true, text: "Sammle 5 Rostsplitter von Wegräubern.", target: "rust", needed: 5, rewardXp: 135, rewardGold: 44 },
  { id: "elites", name: "Mut unter Stein", rarity: "epic", repeatable: true, text: "Besiege 3 Elite-Gegner.", target: "elite", needed: 3, rewardXp: 360, rewardGold: 95 },
  { id: "boars", name: "Dornen im Acker", rarity: "common", repeatable: true, text: "Erlege 7 Dornenkeiler.", target: "beast", needed: 7, rewardXp: 190, rewardGold: 55 },
  { id: "dungeon", name: "Licht unter Stein", rarity: "epic", repeatable: true, text: "Besiege 8 Dungeon-Gegner.", target: "dungeon", needed: 8, rewardXp: 330, rewardGold: 88 },
  { id: "bandits", name: "Wege wieder sicher", rarity: "rare", repeatable: true, text: "Besiege 9 Wegräuber.", target: "bandit", needed: 9, rewardXp: 155, rewardGold: 50 },
  { id: "fields", name: "Nebel über den Feldern", rarity: "rare", repeatable: true, text: "Vertreibe 6 Gegner aus den verfluchten Feldern.", target: "field", needed: 6, rewardXp: 260, rewardGold: 78 },
  { id: "ash", name: "Asche im Wind", rarity: "epic", repeatable: true, text: "Besiege 6 Gegner im Aschengrund.", target: "ash", needed: 6, rewardXp: 520, rewardGold: 135 },
];

const rareQuestTemplates = [
  { key: "wolf", name: "Blutspur des Rudels", rarity: "legendary", text: "Jage 9 Waldwölfe für eine alte Jagdtrophaee.", target: "wolf", needed: 9, rewardXp: 260, rewardGold: 75, slot: "necklace" },
  { key: "bandit", name: "Versiegelter Steckbrief", rarity: "legendary", text: "Besiege 8 Wegräuber und bringe den Steckbrief zurück.", target: "bandit", needed: 8, rewardXp: 310, rewardGold: 95, slot: "weapon" },
  { key: "elite", name: "Schwur gegen die Gefallenen", rarity: "legendary", text: "Bezwinge 4 Elite-Gegner für eine seltene Reliquie.", target: "elite", needed: 4, rewardXp: 620, rewardGold: 150, slot: "chest" },
  { key: "dungeon", name: "Runen aus der Tiefe", rarity: "legendary", text: "Besiege 7 Dungeon-Gegner und berge eine Runenbelohnung.", target: "dungeon", needed: 7, rewardXp: 540, rewardGold: 130, slot: "ring" },
  { key: "ash", name: "Schwarzer Chor", rarity: "legendary", text: "Bezwinge 5 Aschengegner für eine versengte Reliquie.", target: "ash", needed: 5, rewardXp: 760, rewardGold: 190, slot: "necklace" },
];

const allQuestIds = () => [...questCatalog.map((quest) => quest.id), ...Object.keys(state?.rareQuests || {})];

const rarityLabel = {
  common: "Gewöhnlich",
  rare: "Selten",
  epic: "Episch",
  legendary: "Legendär",
};

const materialLabel = {
  scrap: "Eisenstücke",
  leather: "Lederreste",
  cloth: "Stofffetzen",
  chain: "Kettenglieder",
  sinew: "Bestiensehnen",
  shard: "Runensplitter",
  moonDust: "Mondstaub",
  oathSteel: "Eidstahl",
  bone: "Knochenstücke",
  shadowResin: "Schattenharz",
  emberCore: "Glutkern",
  wolfFang: "Rudelfang",
  oathMark: "Eidmarke",
  graveSeal: "Grabessiegel",
  crownAsh: "Kronenasche",
};

const achievementCatalog = [
  { id: "firstElite", category: "Kampf", name: "Erste Narbe", text: "Besiege deinen ersten Elite-Gegner.", metric: "eliteKills", target: 1, reward: { renown: 1, gold: 40 } },
  { id: "eliteBreaker", category: "Kampf", name: "Elitenbrecher", text: "Besiege 10 Elite-Gegner.", metric: "eliteKills", target: 10, reward: { renown: 2, materials: { oathSteel: 3 } } },
  { id: "firstBoss", category: "Kampf", name: "Tor zur Tiefe", text: "Besiege deinen ersten Dungeon-Boss.", metric: "bossKills", target: 1, reward: { renown: 2, materials: { graveSeal: 1 } } },
  { id: "bossHunter", category: "Kampf", name: "Bossjäger", text: "Besiege 5 Dungeon-Bosse.", metric: "bossKills", target: 5, reward: { renown: 3, materials: { crownAsh: 2 } } },
  { id: "tenWins", category: "Kampf", name: "Nicht kleinzukriegen", text: "Gewinne 10 Kämpfe.", metric: "wins", target: 10, reward: { gold: 70, materials: { leather: 2 } } },
  { id: "fiftyWins", category: "Kampf", name: "Grauwacht-Veteran", text: "Gewinne 50 Kämpfe.", metric: "wins", target: 50, reward: { renown: 2, gold: 250 } },

  { id: "tenItems", category: "Loot", name: "Sammlerblick", text: "Entdecke 10 verschiedene Items.", metric: "discoveredItems", target: 10, reward: { gold: 80, materials: { shard: 2 } } },
  { id: "twentyFiveItems", category: "Loot", name: "Schatzsucher", text: "Entdecke 25 verschiedene Items.", metric: "discoveredItems", target: 25, reward: { renown: 1, materials: { moonDust: 3 } } },
  { id: "legendaryFind", category: "Loot", name: "Legendärer Fund", text: "Finde ein legendäres Item.", metric: "legendaryItems", target: 1, reward: { renown: 2, materials: { emberCore: 2 } } },
  { id: "bossTrophy", category: "Loot", name: "Boss-Trophäe", text: "Finde einen festen Boss-Drop.", metric: "fixedBossDrops", target: 1, reward: { renown: 2, materials: { crownAsh: 1 } } },
  { id: "setHunter", category: "Loot", name: "Set-Jäger", text: "Entdecke ein Set-Item.", metric: "setItems", target: 1, reward: { renown: 1, materials: { sinew: 2 } } },

  { id: "anvilTrial", category: "Schmied", name: "Ambossprobe", text: "Bringe ein Item an dein aktuelles Upgrade-Limit.", metric: "itemAtLimit", target: 1, reward: { renown: 1, materials: { scrap: 3 } } },
  { id: "tenUpgrades", category: "Schmied", name: "Stahl will Arbeit", text: "Verbessere Ausrüstung 10-mal.", metric: "itemsUpgraded", target: 10, reward: { gold: 120, materials: { emberCore: 2 } } },
  { id: "smithLimit", category: "Schmied", name: "Meisterstahl", text: "Schalte ein neues Upgrade-Limit frei.", metric: "smithMasteries", target: 1, reward: { renown: 2, materials: { oathSteel: 3 } } },
  { id: "salvager", category: "Schmied", name: "Zerleger", text: "Zerlege 10 Items.", metric: "itemsSalvaged", target: 10, reward: { materials: { shard: 2, moonDust: 2 } } },

  { id: "firstEnchant", category: "Mira", name: "Runenfunke", text: "Verzaubere dein erstes Item.", metric: "itemsEnchanted", target: 1, reward: { materials: { shard: 2, moonDust: 1 } } },
  { id: "secondBinding", category: "Mira", name: "Zweite Bindung", text: "Schalte 2 Verzauberungs-Slots frei.", metric: "enchantSlots", target: 2, reward: { renown: 2, materials: { moonDust: 3 } } },
  { id: "rareEnchant", category: "Mira", name: "Arkane Spur", text: "Wirke oder trage eine seltene Verzauberung.", metric: "rareEnchantments", target: 1, reward: { renown: 1, materials: { shard: 2 } } },
  { id: "miraAlmostSmiles", category: "Mira", name: "Mira lächelt fast", text: "Schließe einen arkanen Auftrag ab.", metric: "enchantMasteries", target: 1, reward: { renown: 2, materials: { crownAsh: 1 } } },

  { id: "knownFighter", category: "Progression", name: "Bekannter Kämpfer", text: "Erreiche 10 Ruhm.", metric: "renown", target: 10, reward: { gold: 150, materials: { oathSteel: 2 } } },
];

const materialDrops = {
  wolf: [{ id: "leather", min: 1, max: 2 }, { id: "sinew", min: 0, max: 1 }],
  bandit: [{ id: "scrap", min: 1, max: 2 }, { id: "cloth", min: 0, max: 1 }, { id: "shard", min: 0, max: 1 }],
  boar: [{ id: "leather", min: 2, max: 3 }, { id: "sinew", min: 1, max: 2 }, { id: "emberCore", min: 0, max: 1 }],
  oldKnight: [{ id: "scrap", min: 2, max: 4 }, { id: "oathSteel", min: 0, max: 1 }],
  roadThief: [{ id: "scrap", min: 2, max: 3 }, { id: "cloth", min: 1, max: 2 }],
  ironHound: [{ id: "scrap", min: 2, max: 4 }, { id: "sinew", min: 1, max: 2 }],
  plagueCrow: [{ id: "bone", min: 1, max: 2 }, { id: "shadowResin", min: 0, max: 1 }],
  fieldWraith: [{ id: "shard", min: 1, max: 2 }, { id: "shadowResin", min: 1, max: 2 }],
  ashMarauder: [{ id: "scrap", min: 3, max: 5 }, { id: "emberCore", min: 0, max: 1 }],
  emberStalker: [{ id: "sinew", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }],
  crownSentinel: [{ id: "oathSteel", min: 2, max: 4 }, { id: "crownAsh", min: 1, max: 2 }],
  ratguard: [{ id: "scrap", min: 2, max: 3 }, { id: "chain", min: 0, max: 1 }],
  boneAcolyte: [{ id: "bone", min: 1, max: 3 }, { id: "shard", min: 1, max: 2 }],
  cryptBrute: [{ id: "chain", min: 2, max: 4 }, { id: "shadowResin", min: 0, max: 1 }],
  chainWarden: [{ id: "chain", min: 2, max: 4 }, { id: "oathSteel", min: 0, max: 1 }],
  oathForger: [{ id: "oathSteel", min: 2, max: 4 }, { id: "emberCore", min: 0, max: 1 }],
  ironDuke: [{ id: "oathSteel", min: 3, max: 5 }, { id: "oathMark", min: 1, max: 2 }],
  emberPriest: [{ id: "shard", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }],
  crownBeast: [{ id: "sinew", min: 3, max: 5 }, { id: "crownAsh", min: 1, max: 2 }],
  hollowChampion: [{ id: "oathSteel", min: 2, max: 4 }, { id: "emberCore", min: 1, max: 2 }, { id: "crownAsh", min: 0, max: 1 }],
};

