const enemyAbilityCatalog = {
  bloodBite: { name: "Blutbiss", text: "Alle 3 Runden: Biss mit Blutung.", type: "active" },
  ambush: { name: "Hinterhalt", text: "Runde 1: deutlich stärkerer erster Treffer.", type: "active" },
  ironBite: { name: "Eisenbiss", text: "Alle 3 Runden: Biss, der deinen nächsten Schlag schwächt.", type: "active" },
  tuskCharge: { name: "Ansturm", text: "Alle 4 Runden: schwerer Treffer.", type: "active" },
  shieldBash: { name: "Schildstoß", text: "Alle 3 Runden: Schaden und dein nächster Angriff wird gedämpft.", type: "active" },
  guardStance: { name: "Schildhaltung", text: "Alle 4 Runden: nimmt deutlich weniger Schaden.", type: "active" },
  poisonClaws: { name: "Giftkrallen", text: "Alle 3 Runden: Gift über mehrere Runden.", type: "active" },
  lifeDrain: { name: "Lebensentzug", text: "Alle 4 Runden: Treffer heilt den Gegner.", type: "active" },
  mistForm: { name: "Nebelform", text: "Alle 4 Runden: dein Angriff wird stark gedämpft.", type: "active" },
  burningBlade: { name: "Brennende Klinge", text: "Alle 3 Runden: Treffer mit Brennen.", type: "active" },
  flameBite: { name: "Flammenbiss", text: "Alle 4 Runden: starker Treffer mit Brennen.", type: "active" },
  emberDodge: { name: "Glutausweichen", text: "Alle 3 Runden: dämpft deinen Treffer.", type: "active" },
  crownShield: { name: "Kronenschild", text: "Alle 4 Runden: reduziert eingehenden Schaden.", type: "active" },
  judgementStrike: { name: "Urteilsschlag", text: "Wenn du wenig Leben hast: gefährlicher Treffer.", type: "active" },
  guardBash: { name: "Wachhieb", text: "Alle 3 Runden: harter Kontrolltreffer.", type: "active" },
  chainHook: { name: "Kettenhaken", text: "Alle 4 Runden: zieht dich aus der Deckung und schwächt deinen Angriff.", type: "active" },
  boneCurse: { name: "Knochenfluch", text: "Alle 3 Runden: senkt deinen nächsten Schaden.", type: "active" },
  graveMend: { name: "Grabheilung", text: "Alle 4 Runden: heilt sich selbst.", type: "active" },
  crushingBlow: { name: "Zertrümmern", text: "Alle 4 Runden: sehr schwerer Treffer.", type: "active" },
  boneArmor: { name: "Knochenpanzer", text: "Alle 4 Runden: nimmt weniger Schaden.", type: "active" },
  forgeSmash: { name: "Amboss-Schlag", text: "Alle 3 Runden: massiver Hammerschlag.", type: "active" },
  emberChains: { name: "Glühende Ketten", text: "Alle 4 Runden: Schaden, Brennen und geschwächter Angriff.", type: "active" },
  hardenArmor: { name: "Rüstung härten", text: "Alle 4 Runden: reduziert deinen nächsten Treffer stark.", type: "active" },
  dukeCommand: { name: "Herzoglicher Befehl", text: "Alle 3 Runden: verstärkter Angriff.", type: "active" },
  ironWall: { name: "Eisenwand", text: "Alle 4 Runden: sehr starke Schadensreduktion.", type: "active" },
  executionOrder: { name: "Richtschlag", text: "Wenn du wenig Leben hast: extrem gefährlicher Treffer.", type: "active" },
  emberPrayer: { name: "Glutgebet", text: "Alle 4 Runden: leichter Treffer und Heilung.", type: "active" },
  ashNova: { name: "Aschennova", text: "Alle 5 Runden: Flächenschaden mit Brennen.", type: "active" },
  crownMaul: { name: "Kronenpranke", text: "Alle 4 Runden: brutaler Prankenhieb.", type: "active" },
  ashBlade: { name: "Aschenklinge", text: "Alle 3 Runden: Feuertreffer mit Brennen.", type: "active" },
  hollowGaze: { name: "Leerer Blick", text: "Alle 4 Runden: schwächt deinen nächsten Angriff.", type: "active" },
  championLeap: { name: "Champion-Sprung", text: "Alle 5 Runden: sehr schwerer Sprungangriff.", type: "active" },
  cellLockdown: { name: "Zellenschluss", text: "Alle 5 Runden: schwacher Treffer, aber dein nächster Angriff wird stark gedämpft.", type: "active" },
  graveTithe: { name: "Grabzehnt", text: "Alle 5 Runden: dunkler Treffer, der den Boss heilt.", type: "active" },
  bruteRampage: { name: "Gruftwut", text: "Unter 55% Leben: alle 3 Runden ein wuchtiger Treffer.", type: "active" },
  wardenVerdict: { name: "Aufseherurteil", text: "Alle 5 Runden: harter Kettenhieb und starke Angriffsschwächung.", type: "active" },
  anvilQuake: { name: "Ambossbeben", text: "Alle 5 Runden: schwerer Feuertreffer mit Brennen.", type: "active" },
  dukeDuel: { name: "Adelsduell", text: "Alle 5 Runden: präziser Hieb mit hoher Gefahr.", type: "active" },
  emberHymn: { name: "Gluthymne", text: "Alle 5 Runden: Feuer, Heilung und anhaltender Brand.", type: "active" },
  royalGore: { name: "Kronensturm", text: "Unter 60% Leben: alle 3 Runden ein brutaler Ansturm.", type: "active" },
  hollowRift: { name: "Leerenspalt", text: "Alle 5 Runden: Rissangriff, der deinen nächsten Schlag stark schwächt.", type: "active" },
  eliteFury: { name: "Elite-Wut", text: "Alle 4 Runden: zusätzlicher Elite-Druck.", type: "active" },
  eliteGuard: { name: "Elite-Deckung", text: "Alle 4 Runden: reduziert deinen Treffer.", type: "active" },
  prisonDiscipline: { name: "Kerkerdisziplin", text: "Passiv: jede 5. Runde weniger eingehender Schaden.", type: "passive" },
  lastGuard: { name: "Standhaft", text: "Passiv: unter 30% Leben nimmt der Gegner weniger Schaden.", type: "passive" },
  unholyRenewal: { name: "Unheilige Erneuerung", text: "Passiv: unter 50% Leben heilen Effekte stärker.", type: "passive" },
  heavyBody: { name: "Schwerer Körper", text: "Passiv: kleine Treffer werden gedämpft.", type: "passive" },
  forgeFire: { name: "Schmiedefeuer", text: "Passiv: unter 50% Leben verursacht der Gegner mehr Schaden.", type: "passive" },
  noblePride: { name: "Adelsstolz", text: "Passiv: unter 40% Leben wird der Herzog gefährlicher.", type: "passive" },
  royalHide: { name: "Kronenhaut", text: "Passiv: dauerhaft etwas weniger eingehender Schaden.", type: "passive" },
  secondPhase: { name: "Zweite Phase", text: "Passiv: unter 50% Leben stärker und zäher.", type: "passive" },
  cellAuthority: { name: "Kerkerautorität", text: "Passiv: die ersten Runden und jede fünfte Runde ist der Boss schwerer zu knacken.", type: "passive" },
  graveBargain: { name: "Grabpakt", text: "Passiv: unter 50% Leben wird Heilung stärker und der Boss zäher.", type: "passive" },
  bruteBulk: { name: "Massiger Leib", text: "Passiv: kleine Treffer prallen besonders stark ab.", type: "passive" },
  wardenPressure: { name: "Kettendruck", text: "Passiv: jede 4. Runde nimmt der Boss weniger Schaden.", type: "passive" },
  oathHeat: { name: "Eidglut", text: "Passiv: unter 50% Leben brennt der Boss härter und schlägt stärker.", type: "passive" },
  dukePride: { name: "Herzogsstolz", text: "Passiv: unter 45% Leben steigen Schaden und Widerstand.", type: "passive" },
  emberChoir: { name: "Glutchor", text: "Passiv: Heilungen sind stärker und Feuerdruck bleibt gefährlich.", type: "passive" },
  crownFrenzy: { name: "Kronenraserei", text: "Passiv: unter 55% Leben steigt der Schaden deutlich.", type: "passive" },
  hollowSecondWind: { name: "Leere Zweite Phase", text: "Passiv: unter 50% Leben wird der Champion stärker und zäher.", type: "passive" },
};

const zones = {
  meadow: {
    name: "Grauwacht-Wald",
    type: "zone",
    range: "Level 1-6",
    unlock: { level: 1, renown: 0 },
    enemies: ["wolf", "bandit", "boar"],
  },
  road: {
    name: "Räuberstraße",
    type: "zone",
    range: "Level 5-11",
    unlock: { level: 5, renown: 0 },
    enemies: ["roadThief", "ironHound", "oldKnight"],
  },
  fields: {
    name: "Verfluchte Felder",
    type: "zone",
    range: "Level 10-16",
    unlock: { level: 9, renown: 8 },
    enemies: ["plagueCrow", "fieldWraith", "oldKnight"],
  },
  ashgrounds: {
    name: "Aschengrund",
    type: "zone",
    range: "Level 15-20",
    unlock: { level: 14, renown: 20 },
    enemies: ["ashMarauder", "emberStalker", "crownSentinel"],
  },
  crypt: {
    name: "Krypta der Grauwacht",
    type: "dungeon",
    range: "Level 9-15",
    unlock: { level: 8, renown: 6 },
    enemies: ["ratguard", "boneAcolyte", "cryptBrute"],
  },
  ironhold: {
    name: "Eisenbruch-Festung",
    type: "dungeon",
    range: "Level 13-18",
    unlock: { level: 12, renown: 14 },
    enemies: ["chainWarden", "oathForger", "ironDuke"],
  },
  ashcathedral: {
    name: "Aschenkathedrale",
    type: "dungeon",
    range: "Level 18-20",
    unlock: { level: 17, renown: 30 },
    enemies: ["emberPriest", "crownBeast", "hollowChampion"],
  },
};

const enemies = {
  wolf: {
    name: "Waldwolf",
    sprite: "enemy-wolf",
    level: 1,
    hp: 44,
    damage: [7, 12],
    defense: 2,
    xp: 16,
    gold: [2, 4],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["common", "rare"] },
    drops: [{ id: "wolfRing", chance: 0.024 }],
    abilities: ["bloodBite"],
    tags: { wolf: 1 },
  },
  bandit: {
    name: "Wegräuber",
    sprite: "enemy-bandit",
    level: 3,
    hp: 72,
    damage: [12, 19],
    defense: 5,
    xp: 30,
    gold: [4, 9],
    generatedLoot: { slots: ["weapon", "offhand", "necklace"], qualities: ["common", "rare"] },
    drops: [{ id: "rustBlade", chance: 0.038 }],
    abilities: ["ambush"],
    tags: { bandit: 1, rust: 0.32 },
  },
  roadThief: {
    name: "Straßenräuber",
    sprite: "enemy-bandit",
    level: 5,
    hp: 108,
    damage: [18, 28],
    defense: 8,
    xp: 52,
    gold: [8, 15],
    generatedLoot: { slots: ["weapon", "offhand", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "tollKnife", chance: 0.034 }],
    abilities: ["ambush"],
    tags: { bandit: 1, rust: 0.45 },
  },
  ironHound: {
    name: "Eisenhund",
    sprite: "enemy-wolf",
    level: 8,
    hp: 168,
    damage: [27, 39],
    defense: 13,
    xp: 86,
    gold: [10, 19],
    generatedLoot: { slots: ["chest", "boots", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "houndGreaves", chance: 0.026 }],
    abilities: ["ironBite"],
    tags: { beast: 1, rust: 0.25 },
  },
  boar: {
    name: "Dornenkeiler",
    sprite: "enemy-boar",
    level: 6,
    hp: 122,
    damage: [20, 31],
    defense: 8,
    xp: 62,
    gold: [7, 13],
    generatedLoot: { slots: ["chest", "pants", "boots"], qualities: ["common", "rare"] },
    drops: [{ id: "hideArmor", chance: 0.032 }],
    abilities: ["tuskCharge"],
    tags: { beast: 1 },
  },
  oldKnight: {
    name: "Alter Grenzritter",
    sprite: "enemy-knight",
    level: 10,
    hp: 210,
    damage: [34, 50],
    defense: 17,
    xp: 120,
    gold: [14, 25],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "oathRing", chance: 0.018 }, { id: "knightPlate", chance: 0.012 }],
    abilities: ["shieldBash", "guardStance"],
    passives: ["lastGuard"],
    elite: true,
    tags: { elite: 1 },
  },
  plagueCrow: {
    name: "Seuchenkrähe",
    sprite: "enemy-acolyte",
    level: 10,
    hp: 205,
    damage: [35, 52],
    defense: 15,
    xp: 128,
    gold: [15, 27],
    generatedLoot: { slots: ["necklace", "ring", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "crowTalisman", chance: 0.024 }],
    abilities: ["poisonClaws"],
    tags: { beast: 1, field: 1 },
  },
  fieldWraith: {
    name: "Feldschemen",
    sprite: "enemy-acolyte",
    level: 13,
    hp: 310,
    damage: [48, 70],
    defense: 23,
    xp: 210,
    gold: [22, 38],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "wraithLantern", chance: 0.022 }],
    abilities: ["lifeDrain", "mistForm"],
    elite: true,
    tags: { elite: 1, field: 1, dungeon: 1 },
  },
  ashMarauder: {
    name: "Aschenmarodeur",
    sprite: "enemy-bandit",
    level: 15,
    hp: 380,
    damage: [60, 86],
    defense: 29,
    xp: 260,
    gold: [30, 52],
    generatedLoot: { slots: ["weapon", "chest", "boots"], qualities: ["rare", "epic"] },
    drops: [{ id: "ashHook", chance: 0.022 }],
    abilities: ["burningBlade"],
    tags: { bandit: 1, ash: 1 },
  },
  emberStalker: {
    name: "Glutpirscher",
    sprite: "enemy-wolf",
    level: 17,
    hp: 470,
    damage: [72, 105],
    defense: 34,
    xp: 355,
    gold: [40, 70],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberClaw", chance: 0.018 }],
    abilities: ["flameBite", "emberDodge"],
    tags: { beast: 1, ash: 1 },
  },
  crownSentinel: {
    name: "Kronenwächter",
    sprite: "enemy-knight",
    level: 19,
    hp: 620,
    damage: [88, 126],
    defense: 43,
    xp: 520,
    gold: [52, 92],
    generatedLoot: { slots: ["offhand", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "sentinelVisor", chance: 0.016 }],
    abilities: ["crownShield", "judgementStrike", "shieldBash"],
    passives: ["lastGuard"],
    elite: true,
    tags: { elite: 1, ash: 1 },
  },
  ratguard: {
    name: "Kellergardist",
    sprite: "enemy-ratguard",
    level: 9,
    hp: 190,
    damage: [32, 47],
    defense: 14,
    xp: 105,
    gold: [11, 22],
    generatedLoot: { slots: ["weapon", "offhand", "chest"], qualities: ["rare", "epic"] },
    drops: [{ id: "guardAxe", chance: 0.06 }, { id: "cellkeeperBulwark", chance: 0.045 }],
    abilities: ["guardBash", "guardStance", "chainHook", "cellLockdown"],
    passives: ["prisonDiscipline", "cellAuthority"],
    firstClear: { renown: 2, gold: 85, materials: { chain: 2, scrap: 4 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  boneAcolyte: {
    name: "Knochenakolyth",
    sprite: "enemy-acolyte",
    level: 12,
    hp: 270,
    damage: [43, 64],
    defense: 20,
    xp: 170,
    gold: [17, 32],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["rare", "epic"] },
    drops: [{ id: "graveRing", chance: 0.054 }, { id: "boneChalice", chance: 0.04 }],
    abilities: ["boneCurse", "graveMend", "lifeDrain", "graveTithe"],
    passives: ["unholyRenewal", "graveBargain"],
    firstClear: { renown: 2, gold: 125, materials: { bone: 5, graveSeal: 1 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  cryptBrute: {
    name: "Gruftschläger",
    sprite: "enemy-brute",
    level: 15,
    hp: 390,
    damage: [62, 92],
    defense: 28,
    xp: 275,
    gold: [27, 48],
    generatedLoot: { slots: ["weapon", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "bruteMail", chance: 0.046 }, { id: "cryptCrusher", chance: 0.036 }],
    abilities: ["crushingBlow", "boneArmor", "tuskCharge", "bruteRampage"],
    passives: ["heavyBody", "bruteBulk"],
    firstClear: { renown: 3, gold: 180, materials: { chain: 4, shadowResin: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  chainWarden: {
    name: "Kettenaufseher",
    sprite: "enemy-knight",
    level: 13,
    hp: 335,
    damage: [52, 76],
    defense: 28,
    xp: 240,
    gold: [26, 45],
    generatedLoot: { slots: ["offhand", "chest", "pants"], qualities: ["rare", "epic"] },
    drops: [{ id: "wardenChain", chance: 0.049 }, { id: "wardenShackle", chance: 0.038 }],
    abilities: ["chainHook", "guardStance", "shieldBash", "wardenVerdict"],
    passives: ["prisonDiscipline", "wardenPressure"],
    firstClear: { renown: 3, gold: 210, materials: { chain: 5, oathSteel: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, bandit: 1 },
  },
  oathForger: {
    name: "Eidschmied",
    sprite: "enemy-brute",
    level: 16,
    hp: 500,
    damage: [70, 102],
    defense: 38,
    xp: 390,
    gold: [42, 76],
    generatedLoot: { slots: ["weapon", "offhand", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "forgeHammer", chance: 0.039 }, { id: "oathMantle", chance: 0.032 }],
    abilities: ["forgeSmash", "emberChains", "hardenArmor", "anvilQuake"],
    passives: ["forgeFire", "oathHeat"],
    firstClear: { renown: 4, gold: 285, materials: { oathSteel: 4, emberCore: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  ironDuke: {
    name: "Herzog Eisenbruch",
    sprite: "enemy-knight",
    level: 18,
    hp: 610,
    damage: [82, 118],
    defense: 46,
    xp: 510,
    gold: [55, 98],
    generatedLoot: { slots: ["weapon", "chest", "necklace"], qualities: ["epic", "legendary"] },
    drops: [{ id: "dukeSignet", chance: 0.036 }, { id: "ironCrownplate", chance: 0.03 }],
    abilities: ["dukeCommand", "ironWall", "executionOrder", "dukeDuel"],
    passives: ["noblePride", "dukePride"],
    firstClear: { renown: 4, gold: 360, materials: { oathMark: 2, oathSteel: 5 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
  emberPriest: {
    name: "Glutpriester",
    sprite: "enemy-acolyte",
    level: 18,
    hp: 540,
    damage: [84, 124],
    defense: 37,
    xp: 475,
    gold: [50, 90],
    generatedLoot: { slots: ["offhand", "necklace", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "emberRosary", chance: 0.036 }, { id: "emberCenser", chance: 0.03 }],
    abilities: ["emberHymn", "emberPrayer", "ashNova", "graveMend"],
    passives: ["forgeFire", "emberChoir"],
    firstClear: { renown: 4, gold: 380, materials: { shard: 6, emberCore: 3 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, ash: 1 },
  },
  crownBeast: {
    name: "Bestie der Krone",
    sprite: "enemy-boar",
    level: 19,
    hp: 720,
    damage: [92, 132],
    defense: 41,
    xp: 560,
    gold: [60, 105],
    generatedLoot: { slots: ["weapon", "boots", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "crownFang", chance: 0.034 }, { id: "royalSpurs", chance: 0.028 }],
    abilities: ["crownMaul", "tuskCharge", "judgementStrike", "royalGore"],
    passives: ["royalHide", "crownFrenzy"],
    firstClear: { renown: 5, gold: 430, materials: { sinew: 6, crownAsh: 3 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1, beast: 1, ash: 1 },
  },
  hollowChampion: {
    name: "Hohler Champion",
    sprite: "enemy-champion",
    level: 20,
    hp: 680,
    damage: [95, 138],
    defense: 44,
    xp: 620,
    gold: [58, 105],
    generatedLoot: { slots: ["weapon", "chest", "ring"], qualities: ["epic", "legendary"] },
    drops: [{ id: "ashenGreatsword", chance: 0.032 }, { id: "crownShard", chance: 0.022 }],
    abilities: ["hollowRift", "ashBlade", "hollowGaze", "championLeap"],
    passives: ["secondPhase", "hollowSecondWind"],
    firstClear: { renown: 6, gold: 520, materials: { crownAsh: 4, emberCore: 3, graveSeal: 2 } },
    boss: true,
    elite: true,
    tags: { elite: 1, dungeon: 1 },
  },
};
